/**
 * /p/$token — the public, read-only sandbox for a shared project.
 *
 * Top-level route, so it escapes the workspace auth gate: anyone with the
 * link can review the build — pages rendered for real, the content model,
 * and collection entries — with no editing, no settings, no workspace nav.
 *
 * A "template" link additionally offers a Clone button (unless the owner
 * turned cloning off), which duplicates the project into a workspace.
 */
import { useEffect, useState } from "react";
import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { createPortal } from "react-dom";
import {
  Blocks,
  Check,
  Copy as CopyIcon,
  Database,
  Eye,
  FileText,
  Layers,
  LinkIcon,
  Lock,
  Monitor,
  Smartphone,
  X,
} from "lucide-react";
import { toast } from "sonner";
import { useCMS } from "@/lib/cms/store";
import { usePages } from "@/lib/cms/pages-store";
import { resolveShare, shareActions, type ShareLink } from "@/lib/cms/share-store";
import { cloneProject } from "@/lib/cms/clone";
import { enableGuest } from "@/lib/guest";
import { SectionRenderer, getSectionDef } from "@/components/cms/editor/sections/SectionSystem";
import { Logo } from "@/components/cms/shell/Logo";
import { cn } from "@/lib/utils";
import type { SchemaFieldType } from "@/lib/cms/types";

export const Route = createFileRoute("/p/$token")({
  component: SharedPreview,
});

type Tab = "pages" | "model" | "content";

function SharedPreview() {
  const { token } = Route.useParams();
  const [ready, setReady] = useState(false);
  const [link, setLink] = useState<ShareLink | undefined>();

  // Resolve client-side only: the token registry lives in localStorage, which
  // the server can't read, so an SSR pass would always 404.
  useEffect(() => {
    const l = resolveShare(token);
    setLink(l);
    if (l) shareActions.recordView(token);
    setReady(true);
  }, [token]);

  if (!ready) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-[color:var(--s2)]">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-muted-foreground/30 border-t-muted-foreground" />
      </div>
    );
  }

  if (!link) return <InvalidLink />;
  return <Sandbox link={link} />;
}

function InvalidLink() {
  return (
    <div className="flex min-h-screen items-center justify-center bg-[color:var(--s2)] px-6">
      <div className="w-full max-w-[360px] text-center">
        <span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-background text-muted-foreground shadow-sm">
          <LinkIcon className="h-6 w-6" />
        </span>
        <h1 className="mt-4 text-[16px] font-semibold text-foreground">This link isn't active</h1>
        <p className="mt-1.5 text-[13px] leading-relaxed text-muted-foreground">
          The preview link may have been turned off or regenerated by its owner. Ask them for a fresh link.
        </p>
      </div>
    </div>
  );
}

function Sandbox({ link }: { link: ShareLink }) {
  const project = useCMS((s) => s.projects.find((p) => p.id === link.projectId));
  const pages = usePages(link.projectId);
  const [tab, setTab] = useState<Tab>("pages");
  const [cloneOpen, setCloneOpen] = useState(false);

  if (!project) return <InvalidLink />;
  const isTemplate = link.kind === "template";
  const canClone = isTemplate && link.cloneEnabled;

  return (
    <div className="flex min-h-screen flex-col bg-[color:var(--s2)] text-foreground">
      {/* Bar */}
      <header className="sticky top-0 z-30 flex h-14 shrink-0 items-center gap-3 border-b border-[color:var(--border-hairline)] bg-background/95 px-4 backdrop-blur">
        <Logo className="h-5 w-auto shrink-0" />
        <div className="mx-1 hidden h-5 w-px bg-[color:var(--border-hairline)] sm:block" />
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="truncate text-[13.5px] font-semibold">{project.name}</span>
            <span className="inline-flex shrink-0 items-center gap-1 rounded-[4px] bg-[color:var(--s2)] px-2 py-0.5 text-[10.5px] font-medium text-muted-foreground">
              <Lock className="h-2.5 w-2.5" /> {isTemplate ? "Template" : "Read-only preview"}
            </span>
          </div>
        </div>
        {canClone && (
          <button
            type="button"
            onClick={() => setCloneOpen(true)}
            className="inline-flex h-8 shrink-0 items-center gap-1.5 rounded-[6px] bg-primary px-3 text-[12.5px] font-semibold text-primary-foreground transition-colors hover:bg-[var(--primary-hover)] active:bg-[var(--primary-pressed)]"
          >
            <CopyIcon className="h-3.5 w-3.5" /> Clone this project
          </button>
        )}
      </header>

      {/* Tabs */}
      <nav className="flex shrink-0 items-center gap-1 border-b border-[color:var(--border-hairline)] bg-background px-3">
        {(
          [
            { id: "pages", label: "Pages", icon: FileText },
            { id: "model", label: "Content model", icon: Blocks },
            { id: "content", label: "Collections", icon: Database },
          ] as const
        ).map((t) => (
          <button
            key={t.id}
            type="button"
            onClick={() => setTab(t.id)}
            className={cn(
              "relative inline-flex h-11 items-center gap-1.5 px-3 text-[13px] font-medium transition-colors",
              tab === t.id ? "text-foreground" : "text-muted-foreground hover:text-foreground",
            )}
          >
            <t.icon className="h-3.5 w-3.5" />
            {t.label}
            {tab === t.id && <span className="absolute inset-x-3 -bottom-px h-[2px] rounded-full bg-primary" />}
          </button>
        ))}
      </nav>

      <div className="min-h-0 flex-1">
        {tab === "pages" && <PagesView pages={pages} />}
        {tab === "model" && <ModelView projectId={link.projectId} />}
        {tab === "content" && <ContentView projectId={link.projectId} />}
      </div>

      <footer className="flex items-center justify-center gap-1.5 border-t border-[color:var(--border-hairline)] bg-background px-4 py-2.5 text-[11.5px] text-muted-foreground">
        <Eye className="h-3 w-3" /> Shared read-only preview · Built with BetterCMS
      </footer>

      {cloneOpen && <CloneDialog project={project} onClose={() => setCloneOpen(false)} />}
    </div>
  );
}

/* ------------------------------------------------------------- pages tab */

function PagesView({ pages }: { pages: ReturnType<typeof usePages> }) {
  const [activePath, setActivePath] = useState(pages[0]?.path ?? "/");
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const active = pages.find((p) => p.path === activePath) ?? pages[0];

  if (!active) {
    return <div className="grid h-full place-items-center py-20 text-[13px] text-muted-foreground">This project has no pages yet.</div>;
  }

  return (
    <div className="flex min-h-0">
      {/* page list */}
      <aside className="hidden w-[220px] shrink-0 border-r border-[color:var(--border-hairline)] bg-background p-2 md:block">
        <div className="px-2 pb-2 pt-1 text-[10.5px] font-semibold uppercase tracking-wide text-muted-foreground">
          {pages.length} {pages.length === 1 ? "page" : "pages"}
        </div>
        {pages.map((p) => (
          <button
            key={p.id}
            type="button"
            onClick={() => setActivePath(p.path)}
            className={cn(
              "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-[12.5px] transition-colors",
              p.path === active.path ? "bg-[color:var(--row-selected)] text-foreground" : "text-muted-foreground hover:bg-[color:var(--row-hover)] hover:text-foreground",
            )}
          >
            <FileText className="h-3.5 w-3.5 shrink-0" />
            <span className="min-w-0 flex-1 truncate">{p.title}</span>
          </button>
        ))}
      </aside>

      {/* canvas */}
      <div className="min-w-0 flex-1 p-4">
        <div className="mb-3 flex items-center justify-between gap-3">
          <div className="min-w-0">
            <div className="truncate text-[13px] font-semibold">{active.title}</div>
            <div className="truncate font-mono text-[11px] text-muted-foreground">{active.path}</div>
          </div>
          <div className="flex items-center gap-0.5 rounded-lg border border-[color:var(--border-hairline)] bg-background p-0.5">
            {(
              [
                { id: "desktop", icon: Monitor },
                { id: "mobile", icon: Smartphone },
              ] as const
            ).map((d) => (
              <button
                key={d.id}
                type="button"
                onClick={() => setDevice(d.id)}
                aria-label={d.id}
                aria-pressed={device === d.id}
                className={cn(
                  "grid h-7 w-7 place-items-center rounded-md transition-colors",
                  device === d.id ? "bg-[color:var(--s2)] text-foreground" : "text-muted-foreground hover:text-foreground",
                )}
              >
                <d.icon className="h-3.5 w-3.5" />
              </button>
            ))}
          </div>
        </div>

        <div className="mx-auto overflow-hidden rounded-xl border border-[color:var(--border-hairline)] bg-white shadow-sm transition-all" style={{ maxWidth: device === "mobile" ? 390 : 1100 }}>
          {/* fake browser chrome — the rendered site stays light in both themes */}
          <div className="flex items-center gap-1.5 border-b border-[#ECEBE9] bg-[#F7F7F7] px-3 py-2">
            <span className="h-2.5 w-2.5 rounded-full bg-[#D9D9D9]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#D9D9D9]" />
            <span className="h-2.5 w-2.5 rounded-full bg-[#D9D9D9]" />
          </div>
          <div className="min-h-[400px]">
            {active.sections.length === 0 ? (
              <div className="grid place-items-center py-24 text-[13px] text-[#A6A6A6]">Empty page</div>
            ) : (
              active.sections.map((s) =>
                getSectionDef(s.type) ? (
                  <div key={s.id} className="[&_*]:cursor-default">
                    <SectionRenderer section={s} editable={false} onEdit={() => {}} />
                  </div>
                ) : null,
              )
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

/* ------------------------------------------------------------- model tab */

const FIELD_TONE: Partial<Record<SchemaFieldType, string>> = {
  reference: "text-violet-600 bg-violet-50 dark:bg-violet-400/10",
  multiReference: "text-violet-600 bg-violet-50 dark:bg-violet-400/10",
  richText: "text-blue-600 bg-blue-50 dark:bg-blue-400/10",
  image: "text-amber-600 bg-amber-50 dark:bg-amber-400/10",
  select: "text-emerald-600 bg-emerald-50 dark:bg-emerald-400/10",
};

function ModelView({ projectId }: { projectId: string }) {
  const cols = useCMS((s) => s.collections.filter((c) => c.projectId === projectId));
  const schemas = useCMS((s) => s.schemas);

  if (cols.length === 0) {
    return <div className="grid h-full place-items-center py-20 text-[13px] text-muted-foreground">No collections in this project.</div>;
  }

  return (
    <div className="mx-auto max-w-[900px] space-y-4 p-4 sm:p-6">
      <p className="text-[12.5px] leading-relaxed text-muted-foreground">
        The content model behind this project: every collection and its fields. Read-only, so you can see exactly how it's structured.
      </p>
      {cols.map((c) => {
        const schema = schemas.find((s) => s.id === c.schemaId);
        const fields = schema?.fields ?? [];
        return (
          <div key={c.id} className="overflow-hidden rounded-xl border border-[color:var(--border-hairline)] bg-background">
            <div className="flex items-center gap-2.5 border-b border-[color:var(--border-hairline)] bg-[color:var(--s2)] px-4 py-2.5">
              <Database className="h-4 w-4 text-muted-foreground" />
              <span className="text-[13.5px] font-semibold">{c.name}</span>
              <span className="font-mono text-[11px] text-muted-foreground">/{c.slug}</span>
              <span className="ml-auto text-[11.5px] tabular-nums text-muted-foreground">{fields.length} fields</span>
            </div>
            <ul className="divide-y divide-[color:var(--border-hairline)]">
              {fields.map((f) => (
                <li key={f.id} className="flex items-center gap-3 px-4 py-2.5">
                  <Layers className="h-3.5 w-3.5 shrink-0 text-muted-foreground/70" />
                  <div className="min-w-0 flex-1">
                    <div className="flex items-center gap-1.5">
                      <span className="truncate text-[13px] font-medium">{f.label}</span>
                      {f.required && <span className="text-[13px] leading-none text-destructive">*</span>}
                    </div>
                    <div className="truncate font-mono text-[10.5px] text-muted-foreground">{f.name}</div>
                  </div>
                  <span className={cn("shrink-0 rounded px-1.5 py-0.5 text-[10.5px] font-medium", FIELD_TONE[f.type] ?? "bg-[color:var(--s2)] text-muted-foreground")}>
                    {f.type}
                  </span>
                </li>
              ))}
            </ul>
          </div>
        );
      })}
    </div>
  );
}

/* ----------------------------------------------------------- content tab */

function ContentView({ projectId }: { projectId: string }) {
  const cols = useCMS((s) => s.collections.filter((c) => c.projectId === projectId));
  const entries = useCMS((s) => s.entries);
  const schemas = useCMS((s) => s.schemas);
  const [activeId, setActiveId] = useState(cols[0]?.id ?? "");
  const active = cols.find((c) => c.id === activeId) ?? cols[0];

  if (!active) {
    return <div className="grid h-full place-items-center py-20 text-[13px] text-muted-foreground">No collections to browse.</div>;
  }

  const schema = schemas.find((s) => s.id === active.schemaId);
  const rows = entries.filter((e) => e.collectionId === active.id);
  const cols2 = (schema?.fields ?? []).filter((f) => !f.hiddenInList).slice(0, 3);

  return (
    <div className="flex min-h-0">
      <aside className="hidden w-[200px] shrink-0 border-r border-[color:var(--border-hairline)] bg-background p-2 md:block">
        {cols.map((c) => (
          <button
            key={c.id}
            type="button"
            onClick={() => setActiveId(c.id)}
            className={cn(
              "flex w-full items-center gap-2 rounded-md px-2 py-1.5 text-left text-[12.5px] transition-colors",
              c.id === active.id ? "bg-[color:var(--row-selected)] text-foreground" : "text-muted-foreground hover:bg-[color:var(--row-hover)] hover:text-foreground",
            )}
          >
            <Database className="h-3.5 w-3.5 shrink-0" />
            <span className="min-w-0 flex-1 truncate">{c.name}</span>
            <span className="shrink-0 text-[10.5px] tabular-nums text-muted-foreground">{entries.filter((e) => e.collectionId === c.id).length}</span>
          </button>
        ))}
      </aside>

      <div className="min-w-0 flex-1 p-4 sm:p-6">
        <div className="mb-3 text-[13px] font-semibold">{active.name} · {rows.length} {rows.length === 1 ? "entry" : "entries"}</div>
        <div className="overflow-hidden rounded-xl border border-[color:var(--border-hairline)] bg-background">
          <div className="overflow-x-auto">
            <table className="w-full text-[12.5px]">
              <thead>
                <tr className="border-b border-[color:var(--border-hairline)] bg-[color:var(--s2)] text-left text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
                  <th className="px-4 py-2.5">Title</th>
                  {cols2.map((f) => (
                    <th key={f.id} className="hidden px-4 py-2.5 sm:table-cell">{f.label}</th>
                  ))}
                  <th className="px-4 py-2.5">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[color:var(--border-hairline)]">
                {rows.map((e) => (
                  <tr key={e.id} className="hover:bg-[var(--row-hover)]">
                    <td className="px-4 py-2.5 font-medium">{e.title}</td>
                    {cols2.map((f) => (
                      <td key={f.id} className="hidden max-w-[220px] truncate px-4 py-2.5 text-muted-foreground sm:table-cell">
                        {formatCell(e.fields[f.name])}
                      </td>
                    ))}
                    <td className="px-4 py-2.5">
                      <span className="inline-flex items-center gap-1.5 text-[12px]">
                        <span className={cn("h-1.5 w-1.5 rounded-full", (e.status ?? "published") === "published" ? "bg-[color:var(--status-live)]" : "bg-muted-foreground/50")} />
                        <span className="text-muted-foreground">{e.status ?? "published"}</span>
                      </span>
                    </td>
                  </tr>
                ))}
                {rows.length === 0 && (
                  <tr>
                    <td colSpan={cols2.length + 2} className="px-4 py-10 text-center text-muted-foreground">No entries.</td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}

function formatCell(v: unknown): string {
  if (v == null) return "-";
  if (typeof v === "boolean") return v ? "Yes" : "No";
  if (typeof v === "object") return Array.isArray(v) ? `${v.length} items` : "…";
  return String(v);
}

/* ------------------------------------------------------------- clone flow */

function CloneDialog({ project, onClose }: { project: { id: string; name: string }; onClose: () => void }) {
  const workspaces = useCMS((s) => s.workspaces);
  const navigate = useNavigate();
  const [targetId, setTargetId] = useState(workspaces[0]?.id ?? "");
  const [name, setName] = useState(`${project.name} copy`);

  function doClone() {
    const target = workspaces.find((w) => w.id === targetId);
    if (!target) return;
    const cloned = cloneProject(project.id, target.id, name.trim() || undefined);
    if (!cloned) {
      toast.error("Couldn't clone this project");
      return;
    }
    // Let them into the app to see their new copy.
    enableGuest();
    toast.success(`Cloned into ${target.name}`);
    onClose();
    navigate({ to: "/w/$workspace/p/$project/content", params: { workspace: target.slug, project: cloned.slug } });
  }

  return createPortal(
    <div className="fixed inset-0 z-[95]">
      <div className="absolute inset-0 bg-[rgba(24,18,16,0.4)]" onMouseDown={onClose} aria-hidden />
      <div role="dialog" aria-modal="true" aria-label={`Clone ${project.name}`} className="absolute left-1/2 top-[10vh] flex max-h-[80vh] w-[min(460px,calc(100vw-24px))] -translate-x-1/2 flex-col overflow-hidden rounded-xl border border-[color:var(--border-hairline)] bg-[color:var(--elevated-modal)] text-foreground shadow-[var(--shadow-3)]">
        <div className="flex items-center gap-2.5 border-b border-[color:var(--border-hairline)] px-4 py-3">
          <span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-[color:var(--s2)] text-muted-foreground">
            <CopyIcon className="h-4 w-4" />
          </span>
          <div className="min-w-0 flex-1">
            <div className="text-[14px] font-semibold">Clone this project</div>
            <div className="truncate text-[11.5px] text-muted-foreground">A full copy lands in your workspace, ready to edit.</div>
          </div>
          <button type="button" onClick={onClose} aria-label="Close" className="grid h-8 w-8 place-items-center rounded-md text-muted-foreground transition-colors hover:bg-[color:var(--color-row-hover)] hover:text-foreground">
            <X className="h-4 w-4" />
          </button>
        </div>
        <div className="min-h-0 flex-1 space-y-3.5 overflow-y-auto p-4">
          <label className="block">
            <div className="mb-1 text-[11.5px] font-medium text-muted-foreground">Project name</div>
            <input value={name} onChange={(e) => setName(e.target.value)} className="h-9 w-full rounded-[8px] border border-[color:var(--color-border)] bg-[color:var(--card)] px-2.5 text-[13px] outline-none transition-[border-color,box-shadow] focus:border-[color:var(--border-strong)] focus:shadow-[var(--shadow-focus)]" />
          </label>
          <div>
            <div className="mb-1 text-[11.5px] font-medium text-muted-foreground">Clone into</div>
            <div className="max-h-[220px] overflow-y-auto rounded-lg border border-[color:var(--color-border)]">
              {workspaces.map((w) => (
                <button
                  key={w.id}
                  type="button"
                  onClick={() => setTargetId(w.id)}
                  className={cn(
                    "flex w-full items-center gap-2.5 border-b border-[color:var(--border-hairline)] px-3 py-2.5 text-left transition-colors last:border-b-0",
                    targetId === w.id ? "bg-[color:color-mix(in_oklab,var(--primary)_7%,transparent)]" : "hover:bg-[color:var(--color-row-hover)]",
                  )}
                >
                  <span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-[color:var(--s2)] text-[11px] font-semibold uppercase text-muted-foreground">{w.name.slice(0, 1)}</span>
                  <span className="min-w-0 flex-1">
                    <span className="block truncate text-[13px] font-medium">{w.name}</span>
                    <span className="block text-[11px] capitalize text-muted-foreground">{w.workspacePlan ?? "free"} plan</span>
                  </span>
                  {targetId === w.id && <Check className="h-4 w-4 shrink-0 text-primary" />}
                </button>
              ))}
            </div>
          </div>
        </div>
        <div className="flex items-center justify-end gap-2 border-t border-[color:var(--border-hairline)] px-4 py-3">
          <button type="button" onClick={onClose} className="h-8 rounded-[6px] px-3 text-[12.5px] font-medium text-muted-foreground transition-colors hover:bg-[color:var(--color-row-hover)]">Cancel</button>
          <button type="button" onClick={doClone} disabled={!targetId} className="h-8 rounded-[6px] bg-primary px-3.5 text-[12.5px] font-semibold text-primary-foreground transition-colors hover:bg-[var(--primary-hover)] active:bg-[var(--primary-pressed)] disabled:cursor-not-allowed disabled:opacity-40">
            Clone project
          </button>
        </div>
      </div>
    </div>,
    document.body,
  );
}
