/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as WorkspaceNewRouteImport } from './routes/workspace.new'
import { Route as WWorkspaceRouteImport } from './routes/w.$workspace'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as DevScrollbarsRouteImport } from './routes/dev.scrollbars'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountEmailRouteImport } from './routes/account.email'
import { Route as AccountConnectionsRouteImport } from './routes/account.connections'
import { Route as WWorkspaceIndexRouteImport } from './routes/w.$workspace.index'
import { Route as WWorkspaceSettingsRouteImport } from './routes/w.$workspace.settings'
import { Route as WWorkspaceRolesRouteImport } from './routes/w.$workspace.roles'
import { Route as WWorkspaceProjectsRouteImport } from './routes/w.$workspace.projects'
import { Route as WWorkspaceMembersRouteImport } from './routes/w.$workspace.members'
import { Route as WWorkspaceAgentRouteImport } from './routes/w.$workspace.agent'
import { Route as WWorkspaceSettingsWebhooksRouteImport } from './routes/w.$workspace.settings.webhooks'
import { Route as WWorkspaceSettingsUsageRouteImport } from './routes/w.$workspace.settings.usage'
import { Route as WWorkspaceSettingsPlansRouteImport } from './routes/w.$workspace.settings.plans'
import { Route as WWorkspaceSettingsNotificationsRouteImport } from './routes/w.$workspace.settings.notifications'
import { Route as WWorkspaceSettingsIntegrationsRouteImport } from './routes/w.$workspace.settings.integrations'
import { Route as WWorkspaceSettingsGeneralRouteImport } from './routes/w.$workspace.settings.general'
import { Route as WWorkspaceSettingsDomainsRouteImport } from './routes/w.$workspace.settings.domains'
import { Route as WWorkspaceSettingsBillingRouteImport } from './routes/w.$workspace.settings.billing'
import { Route as WWorkspaceSettingsApiKeysRouteImport } from './routes/w.$workspace.settings.api-keys'
import { Route as WWorkspaceSettingsAiRouteImport } from './routes/w.$workspace.settings.ai'
import { Route as WWorkspaceSettingsAgentsRouteImport } from './routes/w.$workspace.settings.agents'
import { Route as WWorkspacePProjectRouteImport } from './routes/w.$workspace.p.$project'
import { Route as WWorkspaceSettingsBillingIndexRouteImport } from './routes/w.$workspace.settings.billing.index'
import { Route as WWorkspacePProjectIndexRouteImport } from './routes/w.$workspace.p.$project.index'
import { Route as WWorkspaceSettingsBillingUsageRouteImport } from './routes/w.$workspace.settings.billing.usage'
import { Route as WWorkspaceSettingsBillingPaymentRouteImport } from './routes/w.$workspace.settings.billing.payment'
import { Route as WWorkspaceSettingsBillingInvoicesRouteImport } from './routes/w.$workspace.settings.billing.invoices'
import { Route as WWorkspacePProjectWorkflowRouteImport } from './routes/w.$workspace.p.$project.workflow'
import { Route as WWorkspacePProjectVisualRouteImport } from './routes/w.$workspace.p.$project.visual'
import { Route as WWorkspacePProjectSettingsRouteImport } from './routes/w.$workspace.p.$project.settings'
import { Route as WWorkspacePProjectSeoRouteImport } from './routes/w.$workspace.p.$project.seo'
import { Route as WWorkspacePProjectSearchRouteImport } from './routes/w.$workspace.p.$project.search'
import { Route as WWorkspacePProjectSchemaRouteImport } from './routes/w.$workspace.p.$project.schema'
import { Route as WWorkspacePProjectMediaRouteImport } from './routes/w.$workspace.p.$project.media'
import { Route as WWorkspacePProjectInstructionsRouteImport } from './routes/w.$workspace.p.$project.instructions'
import { Route as WWorkspacePProjectHostingRouteImport } from './routes/w.$workspace.p.$project.hosting'
import { Route as WWorkspacePProjectEditorRouteImport } from './routes/w.$workspace.p.$project.editor'
import { Route as WWorkspacePProjectContentRouteImport } from './routes/w.$workspace.p.$project.content'
import { Route as WWorkspacePProjectAnalyticsRouteImport } from './routes/w.$workspace.p.$project.analytics'
import { Route as WWorkspacePProjectAiRouteImport } from './routes/w.$workspace.p.$project.ai'
import { Route as WWorkspacePProjectAgentRouteImport } from './routes/w.$workspace.p.$project.agent'
import { Route as ApiPublicFormsFormIdSubmitRouteImport } from './routes/api/public/forms.$formId.submit'
import { Route as WWorkspacePProjectFormsIndexRouteImport } from './routes/w.$workspace.p.$project.forms.index'
import { Route as WWorkspacePProjectSettingsWebhooksRouteImport } from './routes/w.$workspace.p.$project.settings.webhooks'
import { Route as WWorkspacePProjectSettingsUsageRouteImport } from './routes/w.$workspace.p.$project.settings.usage'
import { Route as WWorkspacePProjectSettingsSitemapRouteImport } from './routes/w.$workspace.p.$project.settings.sitemap'
import { Route as WWorkspacePProjectSettingsSetupRouteImport } from './routes/w.$workspace.p.$project.settings.setup'
import { Route as WWorkspacePProjectSettingsSeoRouteImport } from './routes/w.$workspace.p.$project.settings.seo'
import { Route as WWorkspacePProjectSettingsRobotsRouteImport } from './routes/w.$workspace.p.$project.settings.robots'
import { Route as WWorkspacePProjectSettingsRedirectsRouteImport } from './routes/w.$workspace.p.$project.settings.redirects'
import { Route as WWorkspacePProjectSettingsPublishingRouteImport } from './routes/w.$workspace.p.$project.settings.publishing'
import { Route as WWorkspacePProjectSettingsPlanRouteImport } from './routes/w.$workspace.p.$project.settings.plan'
import { Route as WWorkspacePProjectSettingsIntegrationsRouteImport } from './routes/w.$workspace.p.$project.settings.integrations'
import { Route as WWorkspacePProjectSettingsGeneralRouteImport } from './routes/w.$workspace.p.$project.settings.general'
import { Route as WWorkspacePProjectSettingsEnvRouteImport } from './routes/w.$workspace.p.$project.settings.env'
import { Route as WWorkspacePProjectSettingsDomainsRouteImport } from './routes/w.$workspace.p.$project.settings.domains'
import { Route as WWorkspacePProjectSettingsDeploymentRouteImport } from './routes/w.$workspace.p.$project.settings.deployment'
import { Route as WWorkspacePProjectSettingsDeliveryRouteImport } from './routes/w.$workspace.p.$project.settings.delivery'
import { Route as WWorkspacePProjectSettingsCodeRouteImport } from './routes/w.$workspace.p.$project.settings.code'
import { Route as WWorkspacePProjectSettingsBrandRouteImport } from './routes/w.$workspace.p.$project.settings.brand'
import { Route as WWorkspacePProjectSettingsBackupsRouteImport } from './routes/w.$workspace.p.$project.settings.backups'
import { Route as WWorkspacePProjectSettingsApiRouteImport } from './routes/w.$workspace.p.$project.settings.api'
import { Route as WWorkspacePProjectSettingsAgentsRouteImport } from './routes/w.$workspace.p.$project.settings.agents'
import { Route as WWorkspacePProjectSettingsAccessRouteImport } from './routes/w.$workspace.p.$project.settings.access'
import { Route as WWorkspacePProjectSeoSitemapRouteImport } from './routes/w.$workspace.p.$project.seo.sitemap'
import { Route as WWorkspacePProjectSeoSearchRouteImport } from './routes/w.$workspace.p.$project.seo.search'
import { Route as WWorkspacePProjectSeoSchemaRouteImport } from './routes/w.$workspace.p.$project.seo.schema'
import { Route as WWorkspacePProjectSeoRssRouteImport } from './routes/w.$workspace.p.$project.seo.rss'
import { Route as WWorkspacePProjectSeoRobotsRouteImport } from './routes/w.$workspace.p.$project.seo.robots'
import { Route as WWorkspacePProjectSeoRedirectsRouteImport } from './routes/w.$workspace.p.$project.seo.redirects'
import { Route as WWorkspacePProjectSeoPagesRouteImport } from './routes/w.$workspace.p.$project.seo.pages'
import { Route as WWorkspacePProjectSeoIssuesRouteImport } from './routes/w.$workspace.p.$project.seo.issues'
import { Route as WWorkspacePProjectSeoDeliveryRouteImport } from './routes/w.$workspace.p.$project.seo.delivery'
import { Route as WWorkspacePProjectFormsFormIdRouteImport } from './routes/w.$workspace.p.$project.forms.$formId'
import { Route as WWorkspacePProjectPagesPageIdSeoRouteImport } from './routes/w.$workspace.p.$project.pages.$pageId.seo'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const WorkspaceNewRoute = WorkspaceNewRouteImport.update({
  id: '/workspace/new',
  path: '/workspace/new',
  getParentRoute: () => rootRouteImport,
} as any)
const WWorkspaceRoute = WWorkspaceRouteImport.update({
  id: '/w/$workspace',
  path: '/w/$workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DevScrollbarsRoute = DevScrollbarsRouteImport.update({
  id: '/dev/scrollbars',
  path: '/dev/scrollbars',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEmailRoute = AccountEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AccountRoute,
} as any)
const AccountConnectionsRoute = AccountConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => AccountRoute,
} as any)
const WWorkspaceIndexRoute = WWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceSettingsRoute = WWorkspaceSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceRolesRoute = WWorkspaceRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceProjectsRoute = WWorkspaceProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceMembersRoute = WWorkspaceMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceAgentRoute = WWorkspaceAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceSettingsWebhooksRoute =
  WWorkspaceSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsUsageRoute = WWorkspaceSettingsUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => WWorkspaceSettingsRoute,
} as any)
const WWorkspaceSettingsPlansRoute = WWorkspaceSettingsPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => WWorkspaceSettingsRoute,
} as any)
const WWorkspaceSettingsNotificationsRoute =
  WWorkspaceSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsIntegrationsRoute =
  WWorkspaceSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsGeneralRoute =
  WWorkspaceSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsDomainsRoute =
  WWorkspaceSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsBillingRoute =
  WWorkspaceSettingsBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsApiKeysRoute =
  WWorkspaceSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspaceSettingsAiRoute = WWorkspaceSettingsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => WWorkspaceSettingsRoute,
} as any)
const WWorkspaceSettingsAgentsRoute =
  WWorkspaceSettingsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => WWorkspaceSettingsRoute,
  } as any)
const WWorkspacePProjectRoute = WWorkspacePProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => WWorkspaceRoute,
} as any)
const WWorkspaceSettingsBillingIndexRoute =
  WWorkspaceSettingsBillingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WWorkspaceSettingsBillingRoute,
  } as any)
const WWorkspacePProjectIndexRoute = WWorkspacePProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WWorkspacePProjectRoute,
} as any)
const WWorkspaceSettingsBillingUsageRoute =
  WWorkspaceSettingsBillingUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => WWorkspaceSettingsBillingRoute,
  } as any)
const WWorkspaceSettingsBillingPaymentRoute =
  WWorkspaceSettingsBillingPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => WWorkspaceSettingsBillingRoute,
  } as any)
const WWorkspaceSettingsBillingInvoicesRoute =
  WWorkspaceSettingsBillingInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => WWorkspaceSettingsBillingRoute,
  } as any)
const WWorkspacePProjectWorkflowRoute =
  WWorkspacePProjectWorkflowRouteImport.update({
    id: '/workflow',
    path: '/workflow',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectVisualRoute =
  WWorkspacePProjectVisualRouteImport.update({
    id: '/visual',
    path: '/visual',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectSettingsRoute =
  WWorkspacePProjectSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectSeoRoute = WWorkspacePProjectSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => WWorkspacePProjectRoute,
} as any)
const WWorkspacePProjectSearchRoute =
  WWorkspacePProjectSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectSchemaRoute =
  WWorkspacePProjectSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectMediaRoute = WWorkspacePProjectMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => WWorkspacePProjectRoute,
} as any)
const WWorkspacePProjectInstructionsRoute =
  WWorkspacePProjectInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectHostingRoute =
  WWorkspacePProjectHostingRouteImport.update({
    id: '/hosting',
    path: '/hosting',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectEditorRoute =
  WWorkspacePProjectEditorRouteImport.update({
    id: '/editor',
    path: '/editor',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectContentRoute =
  WWorkspacePProjectContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectAnalyticsRoute =
  WWorkspacePProjectAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectAiRoute = WWorkspacePProjectAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => WWorkspacePProjectRoute,
} as any)
const WWorkspacePProjectAgentRoute = WWorkspacePProjectAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => WWorkspacePProjectRoute,
} as any)
const ApiPublicFormsFormIdSubmitRoute =
  ApiPublicFormsFormIdSubmitRouteImport.update({
    id: '/api/public/forms/$formId/submit',
    path: '/api/public/forms/$formId/submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const WWorkspacePProjectFormsIndexRoute =
  WWorkspacePProjectFormsIndexRouteImport.update({
    id: '/forms/',
    path: '/forms/',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectSettingsWebhooksRoute =
  WWorkspacePProjectSettingsWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsUsageRoute =
  WWorkspacePProjectSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsSitemapRoute =
  WWorkspacePProjectSettingsSitemapRouteImport.update({
    id: '/sitemap',
    path: '/sitemap',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsSetupRoute =
  WWorkspacePProjectSettingsSetupRouteImport.update({
    id: '/setup',
    path: '/setup',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsSeoRoute =
  WWorkspacePProjectSettingsSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsRobotsRoute =
  WWorkspacePProjectSettingsRobotsRouteImport.update({
    id: '/robots',
    path: '/robots',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsRedirectsRoute =
  WWorkspacePProjectSettingsRedirectsRouteImport.update({
    id: '/redirects',
    path: '/redirects',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsPublishingRoute =
  WWorkspacePProjectSettingsPublishingRouteImport.update({
    id: '/publishing',
    path: '/publishing',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsPlanRoute =
  WWorkspacePProjectSettingsPlanRouteImport.update({
    id: '/plan',
    path: '/plan',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsIntegrationsRoute =
  WWorkspacePProjectSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsGeneralRoute =
  WWorkspacePProjectSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsEnvRoute =
  WWorkspacePProjectSettingsEnvRouteImport.update({
    id: '/env',
    path: '/env',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsDomainsRoute =
  WWorkspacePProjectSettingsDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsDeploymentRoute =
  WWorkspacePProjectSettingsDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsDeliveryRoute =
  WWorkspacePProjectSettingsDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsCodeRoute =
  WWorkspacePProjectSettingsCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsBrandRoute =
  WWorkspacePProjectSettingsBrandRouteImport.update({
    id: '/brand',
    path: '/brand',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsBackupsRoute =
  WWorkspacePProjectSettingsBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsApiRoute =
  WWorkspacePProjectSettingsApiRouteImport.update({
    id: '/api',
    path: '/api',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsAgentsRoute =
  WWorkspacePProjectSettingsAgentsRouteImport.update({
    id: '/agents',
    path: '/agents',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSettingsAccessRoute =
  WWorkspacePProjectSettingsAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => WWorkspacePProjectSettingsRoute,
  } as any)
const WWorkspacePProjectSeoSitemapRoute =
  WWorkspacePProjectSeoSitemapRouteImport.update({
    id: '/sitemap',
    path: '/sitemap',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoSearchRoute =
  WWorkspacePProjectSeoSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoSchemaRoute =
  WWorkspacePProjectSeoSchemaRouteImport.update({
    id: '/schema',
    path: '/schema',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoRssRoute =
  WWorkspacePProjectSeoRssRouteImport.update({
    id: '/rss',
    path: '/rss',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoRobotsRoute =
  WWorkspacePProjectSeoRobotsRouteImport.update({
    id: '/robots',
    path: '/robots',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoRedirectsRoute =
  WWorkspacePProjectSeoRedirectsRouteImport.update({
    id: '/redirects',
    path: '/redirects',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoPagesRoute =
  WWorkspacePProjectSeoPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoIssuesRoute =
  WWorkspacePProjectSeoIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectSeoDeliveryRoute =
  WWorkspacePProjectSeoDeliveryRouteImport.update({
    id: '/delivery',
    path: '/delivery',
    getParentRoute: () => WWorkspacePProjectSeoRoute,
  } as any)
const WWorkspacePProjectFormsFormIdRoute =
  WWorkspacePProjectFormsFormIdRouteImport.update({
    id: '/forms/$formId',
    path: '/forms/$formId',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)
const WWorkspacePProjectPagesPageIdSeoRoute =
  WWorkspacePProjectPagesPageIdSeoRouteImport.update({
    id: '/pages/$pageId/seo',
    path: '/pages/$pageId/seo',
    getParentRoute: () => WWorkspacePProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/dev/scrollbars': typeof DevScrollbarsRoute
  '/p/$token': typeof PTokenRoute
  '/w/$workspace': typeof WWorkspaceRouteWithChildren
  '/workspace/new': typeof WorkspaceNewRoute
  '/account/': typeof AccountIndexRoute
  '/w/$workspace/agent': typeof WWorkspaceAgentRoute
  '/w/$workspace/members': typeof WWorkspaceMembersRoute
  '/w/$workspace/projects': typeof WWorkspaceProjectsRoute
  '/w/$workspace/roles': typeof WWorkspaceRolesRoute
  '/w/$workspace/settings': typeof WWorkspaceSettingsRouteWithChildren
  '/w/$workspace/': typeof WWorkspaceIndexRoute
  '/w/$workspace/p/$project': typeof WWorkspacePProjectRouteWithChildren
  '/w/$workspace/settings/agents': typeof WWorkspaceSettingsAgentsRoute
  '/w/$workspace/settings/ai': typeof WWorkspaceSettingsAiRoute
  '/w/$workspace/settings/api-keys': typeof WWorkspaceSettingsApiKeysRoute
  '/w/$workspace/settings/billing': typeof WWorkspaceSettingsBillingRouteWithChildren
  '/w/$workspace/settings/domains': typeof WWorkspaceSettingsDomainsRoute
  '/w/$workspace/settings/general': typeof WWorkspaceSettingsGeneralRoute
  '/w/$workspace/settings/integrations': typeof WWorkspaceSettingsIntegrationsRoute
  '/w/$workspace/settings/notifications': typeof WWorkspaceSettingsNotificationsRoute
  '/w/$workspace/settings/plans': typeof WWorkspaceSettingsPlansRoute
  '/w/$workspace/settings/usage': typeof WWorkspaceSettingsUsageRoute
  '/w/$workspace/settings/webhooks': typeof WWorkspaceSettingsWebhooksRoute
  '/api/public/forms/$formId/submit': typeof ApiPublicFormsFormIdSubmitRoute
  '/w/$workspace/p/$project/agent': typeof WWorkspacePProjectAgentRoute
  '/w/$workspace/p/$project/ai': typeof WWorkspacePProjectAiRoute
  '/w/$workspace/p/$project/analytics': typeof WWorkspacePProjectAnalyticsRoute
  '/w/$workspace/p/$project/content': typeof WWorkspacePProjectContentRoute
  '/w/$workspace/p/$project/editor': typeof WWorkspacePProjectEditorRoute
  '/w/$workspace/p/$project/hosting': typeof WWorkspacePProjectHostingRoute
  '/w/$workspace/p/$project/instructions': typeof WWorkspacePProjectInstructionsRoute
  '/w/$workspace/p/$project/media': typeof WWorkspacePProjectMediaRoute
  '/w/$workspace/p/$project/schema': typeof WWorkspacePProjectSchemaRoute
  '/w/$workspace/p/$project/search': typeof WWorkspacePProjectSearchRoute
  '/w/$workspace/p/$project/seo': typeof WWorkspacePProjectSeoRouteWithChildren
  '/w/$workspace/p/$project/settings': typeof WWorkspacePProjectSettingsRouteWithChildren
  '/w/$workspace/p/$project/visual': typeof WWorkspacePProjectVisualRoute
  '/w/$workspace/p/$project/workflow': typeof WWorkspacePProjectWorkflowRoute
  '/w/$workspace/settings/billing/invoices': typeof WWorkspaceSettingsBillingInvoicesRoute
  '/w/$workspace/settings/billing/payment': typeof WWorkspaceSettingsBillingPaymentRoute
  '/w/$workspace/settings/billing/usage': typeof WWorkspaceSettingsBillingUsageRoute
  '/w/$workspace/p/$project/': typeof WWorkspacePProjectIndexRoute
  '/w/$workspace/settings/billing/': typeof WWorkspaceSettingsBillingIndexRoute
  '/w/$workspace/p/$project/forms/$formId': typeof WWorkspacePProjectFormsFormIdRoute
  '/w/$workspace/p/$project/seo/delivery': typeof WWorkspacePProjectSeoDeliveryRoute
  '/w/$workspace/p/$project/seo/issues': typeof WWorkspacePProjectSeoIssuesRoute
  '/w/$workspace/p/$project/seo/pages': typeof WWorkspacePProjectSeoPagesRoute
  '/w/$workspace/p/$project/seo/redirects': typeof WWorkspacePProjectSeoRedirectsRoute
  '/w/$workspace/p/$project/seo/robots': typeof WWorkspacePProjectSeoRobotsRoute
  '/w/$workspace/p/$project/seo/rss': typeof WWorkspacePProjectSeoRssRoute
  '/w/$workspace/p/$project/seo/schema': typeof WWorkspacePProjectSeoSchemaRoute
  '/w/$workspace/p/$project/seo/search': typeof WWorkspacePProjectSeoSearchRoute
  '/w/$workspace/p/$project/seo/sitemap': typeof WWorkspacePProjectSeoSitemapRoute
  '/w/$workspace/p/$project/settings/access': typeof WWorkspacePProjectSettingsAccessRoute
  '/w/$workspace/p/$project/settings/agents': typeof WWorkspacePProjectSettingsAgentsRoute
  '/w/$workspace/p/$project/settings/api': typeof WWorkspacePProjectSettingsApiRoute
  '/w/$workspace/p/$project/settings/backups': typeof WWorkspacePProjectSettingsBackupsRoute
  '/w/$workspace/p/$project/settings/brand': typeof WWorkspacePProjectSettingsBrandRoute
  '/w/$workspace/p/$project/settings/code': typeof WWorkspacePProjectSettingsCodeRoute
  '/w/$workspace/p/$project/settings/delivery': typeof WWorkspacePProjectSettingsDeliveryRoute
  '/w/$workspace/p/$project/settings/deployment': typeof WWorkspacePProjectSettingsDeploymentRoute
  '/w/$workspace/p/$project/settings/domains': typeof WWorkspacePProjectSettingsDomainsRoute
  '/w/$workspace/p/$project/settings/env': typeof WWorkspacePProjectSettingsEnvRoute
  '/w/$workspace/p/$project/settings/general': typeof WWorkspacePProjectSettingsGeneralRoute
  '/w/$workspace/p/$project/settings/integrations': typeof WWorkspacePProjectSettingsIntegrationsRoute
  '/w/$workspace/p/$project/settings/plan': typeof WWorkspacePProjectSettingsPlanRoute
  '/w/$workspace/p/$project/settings/publishing': typeof WWorkspacePProjectSettingsPublishingRoute
  '/w/$workspace/p/$project/settings/redirects': typeof WWorkspacePProjectSettingsRedirectsRoute
  '/w/$workspace/p/$project/settings/robots': typeof WWorkspacePProjectSettingsRobotsRoute
  '/w/$workspace/p/$project/settings/seo': typeof WWorkspacePProjectSettingsSeoRoute
  '/w/$workspace/p/$project/settings/setup': typeof WWorkspacePProjectSettingsSetupRoute
  '/w/$workspace/p/$project/settings/sitemap': typeof WWorkspacePProjectSettingsSitemapRoute
  '/w/$workspace/p/$project/settings/usage': typeof WWorkspacePProjectSettingsUsageRoute
  '/w/$workspace/p/$project/settings/webhooks': typeof WWorkspacePProjectSettingsWebhooksRoute
  '/w/$workspace/p/$project/forms/': typeof WWorkspacePProjectFormsIndexRoute
  '/w/$workspace/p/$project/pages/$pageId/seo': typeof WWorkspacePProjectPagesPageIdSeoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/dev/scrollbars': typeof DevScrollbarsRoute
  '/p/$token': typeof PTokenRoute
  '/workspace/new': typeof WorkspaceNewRoute
  '/account': typeof AccountIndexRoute
  '/w/$workspace/agent': typeof WWorkspaceAgentRoute
  '/w/$workspace/members': typeof WWorkspaceMembersRoute
  '/w/$workspace/projects': typeof WWorkspaceProjectsRoute
  '/w/$workspace/roles': typeof WWorkspaceRolesRoute
  '/w/$workspace/settings': typeof WWorkspaceSettingsRouteWithChildren
  '/w/$workspace': typeof WWorkspaceIndexRoute
  '/w/$workspace/settings/agents': typeof WWorkspaceSettingsAgentsRoute
  '/w/$workspace/settings/ai': typeof WWorkspaceSettingsAiRoute
  '/w/$workspace/settings/api-keys': typeof WWorkspaceSettingsApiKeysRoute
  '/w/$workspace/settings/domains': typeof WWorkspaceSettingsDomainsRoute
  '/w/$workspace/settings/general': typeof WWorkspaceSettingsGeneralRoute
  '/w/$workspace/settings/integrations': typeof WWorkspaceSettingsIntegrationsRoute
  '/w/$workspace/settings/notifications': typeof WWorkspaceSettingsNotificationsRoute
  '/w/$workspace/settings/plans': typeof WWorkspaceSettingsPlansRoute
  '/w/$workspace/settings/usage': typeof WWorkspaceSettingsUsageRoute
  '/w/$workspace/settings/webhooks': typeof WWorkspaceSettingsWebhooksRoute
  '/api/public/forms/$formId/submit': typeof ApiPublicFormsFormIdSubmitRoute
  '/w/$workspace/p/$project/agent': typeof WWorkspacePProjectAgentRoute
  '/w/$workspace/p/$project/ai': typeof WWorkspacePProjectAiRoute
  '/w/$workspace/p/$project/analytics': typeof WWorkspacePProjectAnalyticsRoute
  '/w/$workspace/p/$project/content': typeof WWorkspacePProjectContentRoute
  '/w/$workspace/p/$project/editor': typeof WWorkspacePProjectEditorRoute
  '/w/$workspace/p/$project/hosting': typeof WWorkspacePProjectHostingRoute
  '/w/$workspace/p/$project/instructions': typeof WWorkspacePProjectInstructionsRoute
  '/w/$workspace/p/$project/media': typeof WWorkspacePProjectMediaRoute
  '/w/$workspace/p/$project/schema': typeof WWorkspacePProjectSchemaRoute
  '/w/$workspace/p/$project/search': typeof WWorkspacePProjectSearchRoute
  '/w/$workspace/p/$project/seo': typeof WWorkspacePProjectSeoRouteWithChildren
  '/w/$workspace/p/$project/settings': typeof WWorkspacePProjectSettingsRouteWithChildren
  '/w/$workspace/p/$project/visual': typeof WWorkspacePProjectVisualRoute
  '/w/$workspace/p/$project/workflow': typeof WWorkspacePProjectWorkflowRoute
  '/w/$workspace/settings/billing/invoices': typeof WWorkspaceSettingsBillingInvoicesRoute
  '/w/$workspace/settings/billing/payment': typeof WWorkspaceSettingsBillingPaymentRoute
  '/w/$workspace/settings/billing/usage': typeof WWorkspaceSettingsBillingUsageRoute
  '/w/$workspace/p/$project': typeof WWorkspacePProjectIndexRoute
  '/w/$workspace/settings/billing': typeof WWorkspaceSettingsBillingIndexRoute
  '/w/$workspace/p/$project/forms/$formId': typeof WWorkspacePProjectFormsFormIdRoute
  '/w/$workspace/p/$project/seo/delivery': typeof WWorkspacePProjectSeoDeliveryRoute
  '/w/$workspace/p/$project/seo/issues': typeof WWorkspacePProjectSeoIssuesRoute
  '/w/$workspace/p/$project/seo/pages': typeof WWorkspacePProjectSeoPagesRoute
  '/w/$workspace/p/$project/seo/redirects': typeof WWorkspacePProjectSeoRedirectsRoute
  '/w/$workspace/p/$project/seo/robots': typeof WWorkspacePProjectSeoRobotsRoute
  '/w/$workspace/p/$project/seo/rss': typeof WWorkspacePProjectSeoRssRoute
  '/w/$workspace/p/$project/seo/schema': typeof WWorkspacePProjectSeoSchemaRoute
  '/w/$workspace/p/$project/seo/search': typeof WWorkspacePProjectSeoSearchRoute
  '/w/$workspace/p/$project/seo/sitemap': typeof WWorkspacePProjectSeoSitemapRoute
  '/w/$workspace/p/$project/settings/access': typeof WWorkspacePProjectSettingsAccessRoute
  '/w/$workspace/p/$project/settings/agents': typeof WWorkspacePProjectSettingsAgentsRoute
  '/w/$workspace/p/$project/settings/api': typeof WWorkspacePProjectSettingsApiRoute
  '/w/$workspace/p/$project/settings/backups': typeof WWorkspacePProjectSettingsBackupsRoute
  '/w/$workspace/p/$project/settings/brand': typeof WWorkspacePProjectSettingsBrandRoute
  '/w/$workspace/p/$project/settings/code': typeof WWorkspacePProjectSettingsCodeRoute
  '/w/$workspace/p/$project/settings/delivery': typeof WWorkspacePProjectSettingsDeliveryRoute
  '/w/$workspace/p/$project/settings/deployment': typeof WWorkspacePProjectSettingsDeploymentRoute
  '/w/$workspace/p/$project/settings/domains': typeof WWorkspacePProjectSettingsDomainsRoute
  '/w/$workspace/p/$project/settings/env': typeof WWorkspacePProjectSettingsEnvRoute
  '/w/$workspace/p/$project/settings/general': typeof WWorkspacePProjectSettingsGeneralRoute
  '/w/$workspace/p/$project/settings/integrations': typeof WWorkspacePProjectSettingsIntegrationsRoute
  '/w/$workspace/p/$project/settings/plan': typeof WWorkspacePProjectSettingsPlanRoute
  '/w/$workspace/p/$project/settings/publishing': typeof WWorkspacePProjectSettingsPublishingRoute
  '/w/$workspace/p/$project/settings/redirects': typeof WWorkspacePProjectSettingsRedirectsRoute
  '/w/$workspace/p/$project/settings/robots': typeof WWorkspacePProjectSettingsRobotsRoute
  '/w/$workspace/p/$project/settings/seo': typeof WWorkspacePProjectSettingsSeoRoute
  '/w/$workspace/p/$project/settings/setup': typeof WWorkspacePProjectSettingsSetupRoute
  '/w/$workspace/p/$project/settings/sitemap': typeof WWorkspacePProjectSettingsSitemapRoute
  '/w/$workspace/p/$project/settings/usage': typeof WWorkspacePProjectSettingsUsageRoute
  '/w/$workspace/p/$project/settings/webhooks': typeof WWorkspacePProjectSettingsWebhooksRoute
  '/w/$workspace/p/$project/forms': typeof WWorkspacePProjectFormsIndexRoute
  '/w/$workspace/p/$project/pages/$pageId/seo': typeof WWorkspacePProjectPagesPageIdSeoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/account/connections': typeof AccountConnectionsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/dev/scrollbars': typeof DevScrollbarsRoute
  '/p/$token': typeof PTokenRoute
  '/w/$workspace': typeof WWorkspaceRouteWithChildren
  '/workspace/new': typeof WorkspaceNewRoute
  '/account/': typeof AccountIndexRoute
  '/w/$workspace/agent': typeof WWorkspaceAgentRoute
  '/w/$workspace/members': typeof WWorkspaceMembersRoute
  '/w/$workspace/projects': typeof WWorkspaceProjectsRoute
  '/w/$workspace/roles': typeof WWorkspaceRolesRoute
  '/w/$workspace/settings': typeof WWorkspaceSettingsRouteWithChildren
  '/w/$workspace/': typeof WWorkspaceIndexRoute
  '/w/$workspace/p/$project': typeof WWorkspacePProjectRouteWithChildren
  '/w/$workspace/settings/agents': typeof WWorkspaceSettingsAgentsRoute
  '/w/$workspace/settings/ai': typeof WWorkspaceSettingsAiRoute
  '/w/$workspace/settings/api-keys': typeof WWorkspaceSettingsApiKeysRoute
  '/w/$workspace/settings/billing': typeof WWorkspaceSettingsBillingRouteWithChildren
  '/w/$workspace/settings/domains': typeof WWorkspaceSettingsDomainsRoute
  '/w/$workspace/settings/general': typeof WWorkspaceSettingsGeneralRoute
  '/w/$workspace/settings/integrations': typeof WWorkspaceSettingsIntegrationsRoute
  '/w/$workspace/settings/notifications': typeof WWorkspaceSettingsNotificationsRoute
  '/w/$workspace/settings/plans': typeof WWorkspaceSettingsPlansRoute
  '/w/$workspace/settings/usage': typeof WWorkspaceSettingsUsageRoute
  '/w/$workspace/settings/webhooks': typeof WWorkspaceSettingsWebhooksRoute
  '/api/public/forms/$formId/submit': typeof ApiPublicFormsFormIdSubmitRoute
  '/w/$workspace/p/$project/agent': typeof WWorkspacePProjectAgentRoute
  '/w/$workspace/p/$project/ai': typeof WWorkspacePProjectAiRoute
  '/w/$workspace/p/$project/analytics': typeof WWorkspacePProjectAnalyticsRoute
  '/w/$workspace/p/$project/content': typeof WWorkspacePProjectContentRoute
  '/w/$workspace/p/$project/editor': typeof WWorkspacePProjectEditorRoute
  '/w/$workspace/p/$project/hosting': typeof WWorkspacePProjectHostingRoute
  '/w/$workspace/p/$project/instructions': typeof WWorkspacePProjectInstructionsRoute
  '/w/$workspace/p/$project/media': typeof WWorkspacePProjectMediaRoute
  '/w/$workspace/p/$project/schema': typeof WWorkspacePProjectSchemaRoute
  '/w/$workspace/p/$project/search': typeof WWorkspacePProjectSearchRoute
  '/w/$workspace/p/$project/seo': typeof WWorkspacePProjectSeoRouteWithChildren
  '/w/$workspace/p/$project/settings': typeof WWorkspacePProjectSettingsRouteWithChildren
  '/w/$workspace/p/$project/visual': typeof WWorkspacePProjectVisualRoute
  '/w/$workspace/p/$project/workflow': typeof WWorkspacePProjectWorkflowRoute
  '/w/$workspace/settings/billing/invoices': typeof WWorkspaceSettingsBillingInvoicesRoute
  '/w/$workspace/settings/billing/payment': typeof WWorkspaceSettingsBillingPaymentRoute
  '/w/$workspace/settings/billing/usage': typeof WWorkspaceSettingsBillingUsageRoute
  '/w/$workspace/p/$project/': typeof WWorkspacePProjectIndexRoute
  '/w/$workspace/settings/billing/': typeof WWorkspaceSettingsBillingIndexRoute
  '/w/$workspace/p/$project/forms/$formId': typeof WWorkspacePProjectFormsFormIdRoute
  '/w/$workspace/p/$project/seo/delivery': typeof WWorkspacePProjectSeoDeliveryRoute
  '/w/$workspace/p/$project/seo/issues': typeof WWorkspacePProjectSeoIssuesRoute
  '/w/$workspace/p/$project/seo/pages': typeof WWorkspacePProjectSeoPagesRoute
  '/w/$workspace/p/$project/seo/redirects': typeof WWorkspacePProjectSeoRedirectsRoute
  '/w/$workspace/p/$project/seo/robots': typeof WWorkspacePProjectSeoRobotsRoute
  '/w/$workspace/p/$project/seo/rss': typeof WWorkspacePProjectSeoRssRoute
  '/w/$workspace/p/$project/seo/schema': typeof WWorkspacePProjectSeoSchemaRoute
  '/w/$workspace/p/$project/seo/search': typeof WWorkspacePProjectSeoSearchRoute
  '/w/$workspace/p/$project/seo/sitemap': typeof WWorkspacePProjectSeoSitemapRoute
  '/w/$workspace/p/$project/settings/access': typeof WWorkspacePProjectSettingsAccessRoute
  '/w/$workspace/p/$project/settings/agents': typeof WWorkspacePProjectSettingsAgentsRoute
  '/w/$workspace/p/$project/settings/api': typeof WWorkspacePProjectSettingsApiRoute
  '/w/$workspace/p/$project/settings/backups': typeof WWorkspacePProjectSettingsBackupsRoute
  '/w/$workspace/p/$project/settings/brand': typeof WWorkspacePProjectSettingsBrandRoute
  '/w/$workspace/p/$project/settings/code': typeof WWorkspacePProjectSettingsCodeRoute
  '/w/$workspace/p/$project/settings/delivery': typeof WWorkspacePProjectSettingsDeliveryRoute
  '/w/$workspace/p/$project/settings/deployment': typeof WWorkspacePProjectSettingsDeploymentRoute
  '/w/$workspace/p/$project/settings/domains': typeof WWorkspacePProjectSettingsDomainsRoute
  '/w/$workspace/p/$project/settings/env': typeof WWorkspacePProjectSettingsEnvRoute
  '/w/$workspace/p/$project/settings/general': typeof WWorkspacePProjectSettingsGeneralRoute
  '/w/$workspace/p/$project/settings/integrations': typeof WWorkspacePProjectSettingsIntegrationsRoute
  '/w/$workspace/p/$project/settings/plan': typeof WWorkspacePProjectSettingsPlanRoute
  '/w/$workspace/p/$project/settings/publishing': typeof WWorkspacePProjectSettingsPublishingRoute
  '/w/$workspace/p/$project/settings/redirects': typeof WWorkspacePProjectSettingsRedirectsRoute
  '/w/$workspace/p/$project/settings/robots': typeof WWorkspacePProjectSettingsRobotsRoute
  '/w/$workspace/p/$project/settings/seo': typeof WWorkspacePProjectSettingsSeoRoute
  '/w/$workspace/p/$project/settings/setup': typeof WWorkspacePProjectSettingsSetupRoute
  '/w/$workspace/p/$project/settings/sitemap': typeof WWorkspacePProjectSettingsSitemapRoute
  '/w/$workspace/p/$project/settings/usage': typeof WWorkspacePProjectSettingsUsageRoute
  '/w/$workspace/p/$project/settings/webhooks': typeof WWorkspacePProjectSettingsWebhooksRoute
  '/w/$workspace/p/$project/forms/': typeof WWorkspacePProjectFormsIndexRoute
  '/w/$workspace/p/$project/pages/$pageId/seo': typeof WWorkspacePProjectPagesPageIdSeoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/account/connections'
    | '/account/email'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/dev/scrollbars'
    | '/p/$token'
    | '/w/$workspace'
    | '/workspace/new'
    | '/account/'
    | '/w/$workspace/agent'
    | '/w/$workspace/members'
    | '/w/$workspace/projects'
    | '/w/$workspace/roles'
    | '/w/$workspace/settings'
    | '/w/$workspace/'
    | '/w/$workspace/p/$project'
    | '/w/$workspace/settings/agents'
    | '/w/$workspace/settings/ai'
    | '/w/$workspace/settings/api-keys'
    | '/w/$workspace/settings/billing'
    | '/w/$workspace/settings/domains'
    | '/w/$workspace/settings/general'
    | '/w/$workspace/settings/integrations'
    | '/w/$workspace/settings/notifications'
    | '/w/$workspace/settings/plans'
    | '/w/$workspace/settings/usage'
    | '/w/$workspace/settings/webhooks'
    | '/api/public/forms/$formId/submit'
    | '/w/$workspace/p/$project/agent'
    | '/w/$workspace/p/$project/ai'
    | '/w/$workspace/p/$project/analytics'
    | '/w/$workspace/p/$project/content'
    | '/w/$workspace/p/$project/editor'
    | '/w/$workspace/p/$project/hosting'
    | '/w/$workspace/p/$project/instructions'
    | '/w/$workspace/p/$project/media'
    | '/w/$workspace/p/$project/schema'
    | '/w/$workspace/p/$project/search'
    | '/w/$workspace/p/$project/seo'
    | '/w/$workspace/p/$project/settings'
    | '/w/$workspace/p/$project/visual'
    | '/w/$workspace/p/$project/workflow'
    | '/w/$workspace/settings/billing/invoices'
    | '/w/$workspace/settings/billing/payment'
    | '/w/$workspace/settings/billing/usage'
    | '/w/$workspace/p/$project/'
    | '/w/$workspace/settings/billing/'
    | '/w/$workspace/p/$project/forms/$formId'
    | '/w/$workspace/p/$project/seo/delivery'
    | '/w/$workspace/p/$project/seo/issues'
    | '/w/$workspace/p/$project/seo/pages'
    | '/w/$workspace/p/$project/seo/redirects'
    | '/w/$workspace/p/$project/seo/robots'
    | '/w/$workspace/p/$project/seo/rss'
    | '/w/$workspace/p/$project/seo/schema'
    | '/w/$workspace/p/$project/seo/search'
    | '/w/$workspace/p/$project/seo/sitemap'
    | '/w/$workspace/p/$project/settings/access'
    | '/w/$workspace/p/$project/settings/agents'
    | '/w/$workspace/p/$project/settings/api'
    | '/w/$workspace/p/$project/settings/backups'
    | '/w/$workspace/p/$project/settings/brand'
    | '/w/$workspace/p/$project/settings/code'
    | '/w/$workspace/p/$project/settings/delivery'
    | '/w/$workspace/p/$project/settings/deployment'
    | '/w/$workspace/p/$project/settings/domains'
    | '/w/$workspace/p/$project/settings/env'
    | '/w/$workspace/p/$project/settings/general'
    | '/w/$workspace/p/$project/settings/integrations'
    | '/w/$workspace/p/$project/settings/plan'
    | '/w/$workspace/p/$project/settings/publishing'
    | '/w/$workspace/p/$project/settings/redirects'
    | '/w/$workspace/p/$project/settings/robots'
    | '/w/$workspace/p/$project/settings/seo'
    | '/w/$workspace/p/$project/settings/setup'
    | '/w/$workspace/p/$project/settings/sitemap'
    | '/w/$workspace/p/$project/settings/usage'
    | '/w/$workspace/p/$project/settings/webhooks'
    | '/w/$workspace/p/$project/forms/'
    | '/w/$workspace/p/$project/pages/$pageId/seo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/account/connections'
    | '/account/email'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/dev/scrollbars'
    | '/p/$token'
    | '/workspace/new'
    | '/account'
    | '/w/$workspace/agent'
    | '/w/$workspace/members'
    | '/w/$workspace/projects'
    | '/w/$workspace/roles'
    | '/w/$workspace/settings'
    | '/w/$workspace'
    | '/w/$workspace/settings/agents'
    | '/w/$workspace/settings/ai'
    | '/w/$workspace/settings/api-keys'
    | '/w/$workspace/settings/domains'
    | '/w/$workspace/settings/general'
    | '/w/$workspace/settings/integrations'
    | '/w/$workspace/settings/notifications'
    | '/w/$workspace/settings/plans'
    | '/w/$workspace/settings/usage'
    | '/w/$workspace/settings/webhooks'
    | '/api/public/forms/$formId/submit'
    | '/w/$workspace/p/$project/agent'
    | '/w/$workspace/p/$project/ai'
    | '/w/$workspace/p/$project/analytics'
    | '/w/$workspace/p/$project/content'
    | '/w/$workspace/p/$project/editor'
    | '/w/$workspace/p/$project/hosting'
    | '/w/$workspace/p/$project/instructions'
    | '/w/$workspace/p/$project/media'
    | '/w/$workspace/p/$project/schema'
    | '/w/$workspace/p/$project/search'
    | '/w/$workspace/p/$project/seo'
    | '/w/$workspace/p/$project/settings'
    | '/w/$workspace/p/$project/visual'
    | '/w/$workspace/p/$project/workflow'
    | '/w/$workspace/settings/billing/invoices'
    | '/w/$workspace/settings/billing/payment'
    | '/w/$workspace/settings/billing/usage'
    | '/w/$workspace/p/$project'
    | '/w/$workspace/settings/billing'
    | '/w/$workspace/p/$project/forms/$formId'
    | '/w/$workspace/p/$project/seo/delivery'
    | '/w/$workspace/p/$project/seo/issues'
    | '/w/$workspace/p/$project/seo/pages'
    | '/w/$workspace/p/$project/seo/redirects'
    | '/w/$workspace/p/$project/seo/robots'
    | '/w/$workspace/p/$project/seo/rss'
    | '/w/$workspace/p/$project/seo/schema'
    | '/w/$workspace/p/$project/seo/search'
    | '/w/$workspace/p/$project/seo/sitemap'
    | '/w/$workspace/p/$project/settings/access'
    | '/w/$workspace/p/$project/settings/agents'
    | '/w/$workspace/p/$project/settings/api'
    | '/w/$workspace/p/$project/settings/backups'
    | '/w/$workspace/p/$project/settings/brand'
    | '/w/$workspace/p/$project/settings/code'
    | '/w/$workspace/p/$project/settings/delivery'
    | '/w/$workspace/p/$project/settings/deployment'
    | '/w/$workspace/p/$project/settings/domains'
    | '/w/$workspace/p/$project/settings/env'
    | '/w/$workspace/p/$project/settings/general'
    | '/w/$workspace/p/$project/settings/integrations'
    | '/w/$workspace/p/$project/settings/plan'
    | '/w/$workspace/p/$project/settings/publishing'
    | '/w/$workspace/p/$project/settings/redirects'
    | '/w/$workspace/p/$project/settings/robots'
    | '/w/$workspace/p/$project/settings/seo'
    | '/w/$workspace/p/$project/settings/setup'
    | '/w/$workspace/p/$project/settings/sitemap'
    | '/w/$workspace/p/$project/settings/usage'
    | '/w/$workspace/p/$project/settings/webhooks'
    | '/w/$workspace/p/$project/forms'
    | '/w/$workspace/p/$project/pages/$pageId/seo'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/onboarding'
    | '/reset-password'
    | '/account/connections'
    | '/account/email'
    | '/account/preferences'
    | '/account/profile'
    | '/account/security'
    | '/dev/scrollbars'
    | '/p/$token'
    | '/w/$workspace'
    | '/workspace/new'
    | '/account/'
    | '/w/$workspace/agent'
    | '/w/$workspace/members'
    | '/w/$workspace/projects'
    | '/w/$workspace/roles'
    | '/w/$workspace/settings'
    | '/w/$workspace/'
    | '/w/$workspace/p/$project'
    | '/w/$workspace/settings/agents'
    | '/w/$workspace/settings/ai'
    | '/w/$workspace/settings/api-keys'
    | '/w/$workspace/settings/billing'
    | '/w/$workspace/settings/domains'
    | '/w/$workspace/settings/general'
    | '/w/$workspace/settings/integrations'
    | '/w/$workspace/settings/notifications'
    | '/w/$workspace/settings/plans'
    | '/w/$workspace/settings/usage'
    | '/w/$workspace/settings/webhooks'
    | '/api/public/forms/$formId/submit'
    | '/w/$workspace/p/$project/agent'
    | '/w/$workspace/p/$project/ai'
    | '/w/$workspace/p/$project/analytics'
    | '/w/$workspace/p/$project/content'
    | '/w/$workspace/p/$project/editor'
    | '/w/$workspace/p/$project/hosting'
    | '/w/$workspace/p/$project/instructions'
    | '/w/$workspace/p/$project/media'
    | '/w/$workspace/p/$project/schema'
    | '/w/$workspace/p/$project/search'
    | '/w/$workspace/p/$project/seo'
    | '/w/$workspace/p/$project/settings'
    | '/w/$workspace/p/$project/visual'
    | '/w/$workspace/p/$project/workflow'
    | '/w/$workspace/settings/billing/invoices'
    | '/w/$workspace/settings/billing/payment'
    | '/w/$workspace/settings/billing/usage'
    | '/w/$workspace/p/$project/'
    | '/w/$workspace/settings/billing/'
    | '/w/$workspace/p/$project/forms/$formId'
    | '/w/$workspace/p/$project/seo/delivery'
    | '/w/$workspace/p/$project/seo/issues'
    | '/w/$workspace/p/$project/seo/pages'
    | '/w/$workspace/p/$project/seo/redirects'
    | '/w/$workspace/p/$project/seo/robots'
    | '/w/$workspace/p/$project/seo/rss'
    | '/w/$workspace/p/$project/seo/schema'
    | '/w/$workspace/p/$project/seo/search'
    | '/w/$workspace/p/$project/seo/sitemap'
    | '/w/$workspace/p/$project/settings/access'
    | '/w/$workspace/p/$project/settings/agents'
    | '/w/$workspace/p/$project/settings/api'
    | '/w/$workspace/p/$project/settings/backups'
    | '/w/$workspace/p/$project/settings/brand'
    | '/w/$workspace/p/$project/settings/code'
    | '/w/$workspace/p/$project/settings/delivery'
    | '/w/$workspace/p/$project/settings/deployment'
    | '/w/$workspace/p/$project/settings/domains'
    | '/w/$workspace/p/$project/settings/env'
    | '/w/$workspace/p/$project/settings/general'
    | '/w/$workspace/p/$project/settings/integrations'
    | '/w/$workspace/p/$project/settings/plan'
    | '/w/$workspace/p/$project/settings/publishing'
    | '/w/$workspace/p/$project/settings/redirects'
    | '/w/$workspace/p/$project/settings/robots'
    | '/w/$workspace/p/$project/settings/seo'
    | '/w/$workspace/p/$project/settings/setup'
    | '/w/$workspace/p/$project/settings/sitemap'
    | '/w/$workspace/p/$project/settings/usage'
    | '/w/$workspace/p/$project/settings/webhooks'
    | '/w/$workspace/p/$project/forms/'
    | '/w/$workspace/p/$project/pages/$pageId/seo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  DevScrollbarsRoute: typeof DevScrollbarsRoute
  PTokenRoute: typeof PTokenRoute
  WWorkspaceRoute: typeof WWorkspaceRouteWithChildren
  WorkspaceNewRoute: typeof WorkspaceNewRoute
  ApiPublicFormsFormIdSubmitRoute: typeof ApiPublicFormsFormIdSubmitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/workspace/new': {
      id: '/workspace/new'
      path: '/workspace/new'
      fullPath: '/workspace/new'
      preLoaderRoute: typeof WorkspaceNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspace': {
      id: '/w/$workspace'
      path: '/w/$workspace'
      fullPath: '/w/$workspace'
      preLoaderRoute: typeof WWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/scrollbars': {
      id: '/dev/scrollbars'
      path: '/dev/scrollbars'
      fullPath: '/dev/scrollbars'
      preLoaderRoute: typeof DevScrollbarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/email': {
      id: '/account/email'
      path: '/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof AccountEmailRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/connections': {
      id: '/account/connections'
      path: '/connections'
      fullPath: '/account/connections'
      preLoaderRoute: typeof AccountConnectionsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/w/$workspace/': {
      id: '/w/$workspace/'
      path: '/'
      fullPath: '/w/$workspace/'
      preLoaderRoute: typeof WWorkspaceIndexRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/settings': {
      id: '/w/$workspace/settings'
      path: '/settings'
      fullPath: '/w/$workspace/settings'
      preLoaderRoute: typeof WWorkspaceSettingsRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/roles': {
      id: '/w/$workspace/roles'
      path: '/roles'
      fullPath: '/w/$workspace/roles'
      preLoaderRoute: typeof WWorkspaceRolesRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/projects': {
      id: '/w/$workspace/projects'
      path: '/projects'
      fullPath: '/w/$workspace/projects'
      preLoaderRoute: typeof WWorkspaceProjectsRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/members': {
      id: '/w/$workspace/members'
      path: '/members'
      fullPath: '/w/$workspace/members'
      preLoaderRoute: typeof WWorkspaceMembersRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/agent': {
      id: '/w/$workspace/agent'
      path: '/agent'
      fullPath: '/w/$workspace/agent'
      preLoaderRoute: typeof WWorkspaceAgentRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/settings/webhooks': {
      id: '/w/$workspace/settings/webhooks'
      path: '/webhooks'
      fullPath: '/w/$workspace/settings/webhooks'
      preLoaderRoute: typeof WWorkspaceSettingsWebhooksRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/usage': {
      id: '/w/$workspace/settings/usage'
      path: '/usage'
      fullPath: '/w/$workspace/settings/usage'
      preLoaderRoute: typeof WWorkspaceSettingsUsageRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/plans': {
      id: '/w/$workspace/settings/plans'
      path: '/plans'
      fullPath: '/w/$workspace/settings/plans'
      preLoaderRoute: typeof WWorkspaceSettingsPlansRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/notifications': {
      id: '/w/$workspace/settings/notifications'
      path: '/notifications'
      fullPath: '/w/$workspace/settings/notifications'
      preLoaderRoute: typeof WWorkspaceSettingsNotificationsRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/integrations': {
      id: '/w/$workspace/settings/integrations'
      path: '/integrations'
      fullPath: '/w/$workspace/settings/integrations'
      preLoaderRoute: typeof WWorkspaceSettingsIntegrationsRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/general': {
      id: '/w/$workspace/settings/general'
      path: '/general'
      fullPath: '/w/$workspace/settings/general'
      preLoaderRoute: typeof WWorkspaceSettingsGeneralRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/domains': {
      id: '/w/$workspace/settings/domains'
      path: '/domains'
      fullPath: '/w/$workspace/settings/domains'
      preLoaderRoute: typeof WWorkspaceSettingsDomainsRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/billing': {
      id: '/w/$workspace/settings/billing'
      path: '/billing'
      fullPath: '/w/$workspace/settings/billing'
      preLoaderRoute: typeof WWorkspaceSettingsBillingRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/api-keys': {
      id: '/w/$workspace/settings/api-keys'
      path: '/api-keys'
      fullPath: '/w/$workspace/settings/api-keys'
      preLoaderRoute: typeof WWorkspaceSettingsApiKeysRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/ai': {
      id: '/w/$workspace/settings/ai'
      path: '/ai'
      fullPath: '/w/$workspace/settings/ai'
      preLoaderRoute: typeof WWorkspaceSettingsAiRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/settings/agents': {
      id: '/w/$workspace/settings/agents'
      path: '/agents'
      fullPath: '/w/$workspace/settings/agents'
      preLoaderRoute: typeof WWorkspaceSettingsAgentsRouteImport
      parentRoute: typeof WWorkspaceSettingsRoute
    }
    '/w/$workspace/p/$project': {
      id: '/w/$workspace/p/$project'
      path: '/p/$project'
      fullPath: '/w/$workspace/p/$project'
      preLoaderRoute: typeof WWorkspacePProjectRouteImport
      parentRoute: typeof WWorkspaceRoute
    }
    '/w/$workspace/settings/billing/': {
      id: '/w/$workspace/settings/billing/'
      path: '/'
      fullPath: '/w/$workspace/settings/billing/'
      preLoaderRoute: typeof WWorkspaceSettingsBillingIndexRouteImport
      parentRoute: typeof WWorkspaceSettingsBillingRoute
    }
    '/w/$workspace/p/$project/': {
      id: '/w/$workspace/p/$project/'
      path: '/'
      fullPath: '/w/$workspace/p/$project/'
      preLoaderRoute: typeof WWorkspacePProjectIndexRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/settings/billing/usage': {
      id: '/w/$workspace/settings/billing/usage'
      path: '/usage'
      fullPath: '/w/$workspace/settings/billing/usage'
      preLoaderRoute: typeof WWorkspaceSettingsBillingUsageRouteImport
      parentRoute: typeof WWorkspaceSettingsBillingRoute
    }
    '/w/$workspace/settings/billing/payment': {
      id: '/w/$workspace/settings/billing/payment'
      path: '/payment'
      fullPath: '/w/$workspace/settings/billing/payment'
      preLoaderRoute: typeof WWorkspaceSettingsBillingPaymentRouteImport
      parentRoute: typeof WWorkspaceSettingsBillingRoute
    }
    '/w/$workspace/settings/billing/invoices': {
      id: '/w/$workspace/settings/billing/invoices'
      path: '/invoices'
      fullPath: '/w/$workspace/settings/billing/invoices'
      preLoaderRoute: typeof WWorkspaceSettingsBillingInvoicesRouteImport
      parentRoute: typeof WWorkspaceSettingsBillingRoute
    }
    '/w/$workspace/p/$project/workflow': {
      id: '/w/$workspace/p/$project/workflow'
      path: '/workflow'
      fullPath: '/w/$workspace/p/$project/workflow'
      preLoaderRoute: typeof WWorkspacePProjectWorkflowRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/visual': {
      id: '/w/$workspace/p/$project/visual'
      path: '/visual'
      fullPath: '/w/$workspace/p/$project/visual'
      preLoaderRoute: typeof WWorkspacePProjectVisualRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/settings': {
      id: '/w/$workspace/p/$project/settings'
      path: '/settings'
      fullPath: '/w/$workspace/p/$project/settings'
      preLoaderRoute: typeof WWorkspacePProjectSettingsRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/seo': {
      id: '/w/$workspace/p/$project/seo'
      path: '/seo'
      fullPath: '/w/$workspace/p/$project/seo'
      preLoaderRoute: typeof WWorkspacePProjectSeoRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/search': {
      id: '/w/$workspace/p/$project/search'
      path: '/search'
      fullPath: '/w/$workspace/p/$project/search'
      preLoaderRoute: typeof WWorkspacePProjectSearchRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/schema': {
      id: '/w/$workspace/p/$project/schema'
      path: '/schema'
      fullPath: '/w/$workspace/p/$project/schema'
      preLoaderRoute: typeof WWorkspacePProjectSchemaRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/media': {
      id: '/w/$workspace/p/$project/media'
      path: '/media'
      fullPath: '/w/$workspace/p/$project/media'
      preLoaderRoute: typeof WWorkspacePProjectMediaRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/instructions': {
      id: '/w/$workspace/p/$project/instructions'
      path: '/instructions'
      fullPath: '/w/$workspace/p/$project/instructions'
      preLoaderRoute: typeof WWorkspacePProjectInstructionsRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/hosting': {
      id: '/w/$workspace/p/$project/hosting'
      path: '/hosting'
      fullPath: '/w/$workspace/p/$project/hosting'
      preLoaderRoute: typeof WWorkspacePProjectHostingRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/editor': {
      id: '/w/$workspace/p/$project/editor'
      path: '/editor'
      fullPath: '/w/$workspace/p/$project/editor'
      preLoaderRoute: typeof WWorkspacePProjectEditorRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/content': {
      id: '/w/$workspace/p/$project/content'
      path: '/content'
      fullPath: '/w/$workspace/p/$project/content'
      preLoaderRoute: typeof WWorkspacePProjectContentRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/analytics': {
      id: '/w/$workspace/p/$project/analytics'
      path: '/analytics'
      fullPath: '/w/$workspace/p/$project/analytics'
      preLoaderRoute: typeof WWorkspacePProjectAnalyticsRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/ai': {
      id: '/w/$workspace/p/$project/ai'
      path: '/ai'
      fullPath: '/w/$workspace/p/$project/ai'
      preLoaderRoute: typeof WWorkspacePProjectAiRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/agent': {
      id: '/w/$workspace/p/$project/agent'
      path: '/agent'
      fullPath: '/w/$workspace/p/$project/agent'
      preLoaderRoute: typeof WWorkspacePProjectAgentRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/api/public/forms/$formId/submit': {
      id: '/api/public/forms/$formId/submit'
      path: '/api/public/forms/$formId/submit'
      fullPath: '/api/public/forms/$formId/submit'
      preLoaderRoute: typeof ApiPublicFormsFormIdSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$workspace/p/$project/forms/': {
      id: '/w/$workspace/p/$project/forms/'
      path: '/forms'
      fullPath: '/w/$workspace/p/$project/forms/'
      preLoaderRoute: typeof WWorkspacePProjectFormsIndexRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/settings/webhooks': {
      id: '/w/$workspace/p/$project/settings/webhooks'
      path: '/webhooks'
      fullPath: '/w/$workspace/p/$project/settings/webhooks'
      preLoaderRoute: typeof WWorkspacePProjectSettingsWebhooksRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/usage': {
      id: '/w/$workspace/p/$project/settings/usage'
      path: '/usage'
      fullPath: '/w/$workspace/p/$project/settings/usage'
      preLoaderRoute: typeof WWorkspacePProjectSettingsUsageRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/sitemap': {
      id: '/w/$workspace/p/$project/settings/sitemap'
      path: '/sitemap'
      fullPath: '/w/$workspace/p/$project/settings/sitemap'
      preLoaderRoute: typeof WWorkspacePProjectSettingsSitemapRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/setup': {
      id: '/w/$workspace/p/$project/settings/setup'
      path: '/setup'
      fullPath: '/w/$workspace/p/$project/settings/setup'
      preLoaderRoute: typeof WWorkspacePProjectSettingsSetupRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/seo': {
      id: '/w/$workspace/p/$project/settings/seo'
      path: '/seo'
      fullPath: '/w/$workspace/p/$project/settings/seo'
      preLoaderRoute: typeof WWorkspacePProjectSettingsSeoRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/robots': {
      id: '/w/$workspace/p/$project/settings/robots'
      path: '/robots'
      fullPath: '/w/$workspace/p/$project/settings/robots'
      preLoaderRoute: typeof WWorkspacePProjectSettingsRobotsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/redirects': {
      id: '/w/$workspace/p/$project/settings/redirects'
      path: '/redirects'
      fullPath: '/w/$workspace/p/$project/settings/redirects'
      preLoaderRoute: typeof WWorkspacePProjectSettingsRedirectsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/publishing': {
      id: '/w/$workspace/p/$project/settings/publishing'
      path: '/publishing'
      fullPath: '/w/$workspace/p/$project/settings/publishing'
      preLoaderRoute: typeof WWorkspacePProjectSettingsPublishingRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/plan': {
      id: '/w/$workspace/p/$project/settings/plan'
      path: '/plan'
      fullPath: '/w/$workspace/p/$project/settings/plan'
      preLoaderRoute: typeof WWorkspacePProjectSettingsPlanRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/integrations': {
      id: '/w/$workspace/p/$project/settings/integrations'
      path: '/integrations'
      fullPath: '/w/$workspace/p/$project/settings/integrations'
      preLoaderRoute: typeof WWorkspacePProjectSettingsIntegrationsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/general': {
      id: '/w/$workspace/p/$project/settings/general'
      path: '/general'
      fullPath: '/w/$workspace/p/$project/settings/general'
      preLoaderRoute: typeof WWorkspacePProjectSettingsGeneralRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/env': {
      id: '/w/$workspace/p/$project/settings/env'
      path: '/env'
      fullPath: '/w/$workspace/p/$project/settings/env'
      preLoaderRoute: typeof WWorkspacePProjectSettingsEnvRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/domains': {
      id: '/w/$workspace/p/$project/settings/domains'
      path: '/domains'
      fullPath: '/w/$workspace/p/$project/settings/domains'
      preLoaderRoute: typeof WWorkspacePProjectSettingsDomainsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/deployment': {
      id: '/w/$workspace/p/$project/settings/deployment'
      path: '/deployment'
      fullPath: '/w/$workspace/p/$project/settings/deployment'
      preLoaderRoute: typeof WWorkspacePProjectSettingsDeploymentRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/delivery': {
      id: '/w/$workspace/p/$project/settings/delivery'
      path: '/delivery'
      fullPath: '/w/$workspace/p/$project/settings/delivery'
      preLoaderRoute: typeof WWorkspacePProjectSettingsDeliveryRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/code': {
      id: '/w/$workspace/p/$project/settings/code'
      path: '/code'
      fullPath: '/w/$workspace/p/$project/settings/code'
      preLoaderRoute: typeof WWorkspacePProjectSettingsCodeRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/brand': {
      id: '/w/$workspace/p/$project/settings/brand'
      path: '/brand'
      fullPath: '/w/$workspace/p/$project/settings/brand'
      preLoaderRoute: typeof WWorkspacePProjectSettingsBrandRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/backups': {
      id: '/w/$workspace/p/$project/settings/backups'
      path: '/backups'
      fullPath: '/w/$workspace/p/$project/settings/backups'
      preLoaderRoute: typeof WWorkspacePProjectSettingsBackupsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/api': {
      id: '/w/$workspace/p/$project/settings/api'
      path: '/api'
      fullPath: '/w/$workspace/p/$project/settings/api'
      preLoaderRoute: typeof WWorkspacePProjectSettingsApiRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/agents': {
      id: '/w/$workspace/p/$project/settings/agents'
      path: '/agents'
      fullPath: '/w/$workspace/p/$project/settings/agents'
      preLoaderRoute: typeof WWorkspacePProjectSettingsAgentsRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/settings/access': {
      id: '/w/$workspace/p/$project/settings/access'
      path: '/access'
      fullPath: '/w/$workspace/p/$project/settings/access'
      preLoaderRoute: typeof WWorkspacePProjectSettingsAccessRouteImport
      parentRoute: typeof WWorkspacePProjectSettingsRoute
    }
    '/w/$workspace/p/$project/seo/sitemap': {
      id: '/w/$workspace/p/$project/seo/sitemap'
      path: '/sitemap'
      fullPath: '/w/$workspace/p/$project/seo/sitemap'
      preLoaderRoute: typeof WWorkspacePProjectSeoSitemapRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/search': {
      id: '/w/$workspace/p/$project/seo/search'
      path: '/search'
      fullPath: '/w/$workspace/p/$project/seo/search'
      preLoaderRoute: typeof WWorkspacePProjectSeoSearchRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/schema': {
      id: '/w/$workspace/p/$project/seo/schema'
      path: '/schema'
      fullPath: '/w/$workspace/p/$project/seo/schema'
      preLoaderRoute: typeof WWorkspacePProjectSeoSchemaRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/rss': {
      id: '/w/$workspace/p/$project/seo/rss'
      path: '/rss'
      fullPath: '/w/$workspace/p/$project/seo/rss'
      preLoaderRoute: typeof WWorkspacePProjectSeoRssRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/robots': {
      id: '/w/$workspace/p/$project/seo/robots'
      path: '/robots'
      fullPath: '/w/$workspace/p/$project/seo/robots'
      preLoaderRoute: typeof WWorkspacePProjectSeoRobotsRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/redirects': {
      id: '/w/$workspace/p/$project/seo/redirects'
      path: '/redirects'
      fullPath: '/w/$workspace/p/$project/seo/redirects'
      preLoaderRoute: typeof WWorkspacePProjectSeoRedirectsRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/pages': {
      id: '/w/$workspace/p/$project/seo/pages'
      path: '/pages'
      fullPath: '/w/$workspace/p/$project/seo/pages'
      preLoaderRoute: typeof WWorkspacePProjectSeoPagesRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/issues': {
      id: '/w/$workspace/p/$project/seo/issues'
      path: '/issues'
      fullPath: '/w/$workspace/p/$project/seo/issues'
      preLoaderRoute: typeof WWorkspacePProjectSeoIssuesRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/seo/delivery': {
      id: '/w/$workspace/p/$project/seo/delivery'
      path: '/delivery'
      fullPath: '/w/$workspace/p/$project/seo/delivery'
      preLoaderRoute: typeof WWorkspacePProjectSeoDeliveryRouteImport
      parentRoute: typeof WWorkspacePProjectSeoRoute
    }
    '/w/$workspace/p/$project/forms/$formId': {
      id: '/w/$workspace/p/$project/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/w/$workspace/p/$project/forms/$formId'
      preLoaderRoute: typeof WWorkspacePProjectFormsFormIdRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
    '/w/$workspace/p/$project/pages/$pageId/seo': {
      id: '/w/$workspace/p/$project/pages/$pageId/seo'
      path: '/pages/$pageId/seo'
      fullPath: '/w/$workspace/p/$project/pages/$pageId/seo'
      preLoaderRoute: typeof WWorkspacePProjectPagesPageIdSeoRouteImport
      parentRoute: typeof WWorkspacePProjectRoute
    }
  }
}

interface AccountRouteChildren {
  AccountConnectionsRoute: typeof AccountConnectionsRoute
  AccountEmailRoute: typeof AccountEmailRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountConnectionsRoute: AccountConnectionsRoute,
  AccountEmailRoute: AccountEmailRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface WWorkspaceSettingsBillingRouteChildren {
  WWorkspaceSettingsBillingInvoicesRoute: typeof WWorkspaceSettingsBillingInvoicesRoute
  WWorkspaceSettingsBillingPaymentRoute: typeof WWorkspaceSettingsBillingPaymentRoute
  WWorkspaceSettingsBillingUsageRoute: typeof WWorkspaceSettingsBillingUsageRoute
  WWorkspaceSettingsBillingIndexRoute: typeof WWorkspaceSettingsBillingIndexRoute
}

const WWorkspaceSettingsBillingRouteChildren: WWorkspaceSettingsBillingRouteChildren =
  {
    WWorkspaceSettingsBillingInvoicesRoute:
      WWorkspaceSettingsBillingInvoicesRoute,
    WWorkspaceSettingsBillingPaymentRoute:
      WWorkspaceSettingsBillingPaymentRoute,
    WWorkspaceSettingsBillingUsageRoute: WWorkspaceSettingsBillingUsageRoute,
    WWorkspaceSettingsBillingIndexRoute: WWorkspaceSettingsBillingIndexRoute,
  }

const WWorkspaceSettingsBillingRouteWithChildren =
  WWorkspaceSettingsBillingRoute._addFileChildren(
    WWorkspaceSettingsBillingRouteChildren,
  )

interface WWorkspaceSettingsRouteChildren {
  WWorkspaceSettingsAgentsRoute: typeof WWorkspaceSettingsAgentsRoute
  WWorkspaceSettingsAiRoute: typeof WWorkspaceSettingsAiRoute
  WWorkspaceSettingsApiKeysRoute: typeof WWorkspaceSettingsApiKeysRoute
  WWorkspaceSettingsBillingRoute: typeof WWorkspaceSettingsBillingRouteWithChildren
  WWorkspaceSettingsDomainsRoute: typeof WWorkspaceSettingsDomainsRoute
  WWorkspaceSettingsGeneralRoute: typeof WWorkspaceSettingsGeneralRoute
  WWorkspaceSettingsIntegrationsRoute: typeof WWorkspaceSettingsIntegrationsRoute
  WWorkspaceSettingsNotificationsRoute: typeof WWorkspaceSettingsNotificationsRoute
  WWorkspaceSettingsPlansRoute: typeof WWorkspaceSettingsPlansRoute
  WWorkspaceSettingsUsageRoute: typeof WWorkspaceSettingsUsageRoute
  WWorkspaceSettingsWebhooksRoute: typeof WWorkspaceSettingsWebhooksRoute
}

const WWorkspaceSettingsRouteChildren: WWorkspaceSettingsRouteChildren = {
  WWorkspaceSettingsAgentsRoute: WWorkspaceSettingsAgentsRoute,
  WWorkspaceSettingsAiRoute: WWorkspaceSettingsAiRoute,
  WWorkspaceSettingsApiKeysRoute: WWorkspaceSettingsApiKeysRoute,
  WWorkspaceSettingsBillingRoute: WWorkspaceSettingsBillingRouteWithChildren,
  WWorkspaceSettingsDomainsRoute: WWorkspaceSettingsDomainsRoute,
  WWorkspaceSettingsGeneralRoute: WWorkspaceSettingsGeneralRoute,
  WWorkspaceSettingsIntegrationsRoute: WWorkspaceSettingsIntegrationsRoute,
  WWorkspaceSettingsNotificationsRoute: WWorkspaceSettingsNotificationsRoute,
  WWorkspaceSettingsPlansRoute: WWorkspaceSettingsPlansRoute,
  WWorkspaceSettingsUsageRoute: WWorkspaceSettingsUsageRoute,
  WWorkspaceSettingsWebhooksRoute: WWorkspaceSettingsWebhooksRoute,
}

const WWorkspaceSettingsRouteWithChildren =
  WWorkspaceSettingsRoute._addFileChildren(WWorkspaceSettingsRouteChildren)

interface WWorkspacePProjectSeoRouteChildren {
  WWorkspacePProjectSeoDeliveryRoute: typeof WWorkspacePProjectSeoDeliveryRoute
  WWorkspacePProjectSeoIssuesRoute: typeof WWorkspacePProjectSeoIssuesRoute
  WWorkspacePProjectSeoPagesRoute: typeof WWorkspacePProjectSeoPagesRoute
  WWorkspacePProjectSeoRedirectsRoute: typeof WWorkspacePProjectSeoRedirectsRoute
  WWorkspacePProjectSeoRobotsRoute: typeof WWorkspacePProjectSeoRobotsRoute
  WWorkspacePProjectSeoRssRoute: typeof WWorkspacePProjectSeoRssRoute
  WWorkspacePProjectSeoSchemaRoute: typeof WWorkspacePProjectSeoSchemaRoute
  WWorkspacePProjectSeoSearchRoute: typeof WWorkspacePProjectSeoSearchRoute
  WWorkspacePProjectSeoSitemapRoute: typeof WWorkspacePProjectSeoSitemapRoute
}

const WWorkspacePProjectSeoRouteChildren: WWorkspacePProjectSeoRouteChildren = {
  WWorkspacePProjectSeoDeliveryRoute: WWorkspacePProjectSeoDeliveryRoute,
  WWorkspacePProjectSeoIssuesRoute: WWorkspacePProjectSeoIssuesRoute,
  WWorkspacePProjectSeoPagesRoute: WWorkspacePProjectSeoPagesRoute,
  WWorkspacePProjectSeoRedirectsRoute: WWorkspacePProjectSeoRedirectsRoute,
  WWorkspacePProjectSeoRobotsRoute: WWorkspacePProjectSeoRobotsRoute,
  WWorkspacePProjectSeoRssRoute: WWorkspacePProjectSeoRssRoute,
  WWorkspacePProjectSeoSchemaRoute: WWorkspacePProjectSeoSchemaRoute,
  WWorkspacePProjectSeoSearchRoute: WWorkspacePProjectSeoSearchRoute,
  WWorkspacePProjectSeoSitemapRoute: WWorkspacePProjectSeoSitemapRoute,
}

const WWorkspacePProjectSeoRouteWithChildren =
  WWorkspacePProjectSeoRoute._addFileChildren(
    WWorkspacePProjectSeoRouteChildren,
  )

interface WWorkspacePProjectSettingsRouteChildren {
  WWorkspacePProjectSettingsAccessRoute: typeof WWorkspacePProjectSettingsAccessRoute
  WWorkspacePProjectSettingsAgentsRoute: typeof WWorkspacePProjectSettingsAgentsRoute
  WWorkspacePProjectSettingsApiRoute: typeof WWorkspacePProjectSettingsApiRoute
  WWorkspacePProjectSettingsBackupsRoute: typeof WWorkspacePProjectSettingsBackupsRoute
  WWorkspacePProjectSettingsBrandRoute: typeof WWorkspacePProjectSettingsBrandRoute
  WWorkspacePProjectSettingsCodeRoute: typeof WWorkspacePProjectSettingsCodeRoute
  WWorkspacePProjectSettingsDeliveryRoute: typeof WWorkspacePProjectSettingsDeliveryRoute
  WWorkspacePProjectSettingsDeploymentRoute: typeof WWorkspacePProjectSettingsDeploymentRoute
  WWorkspacePProjectSettingsDomainsRoute: typeof WWorkspacePProjectSettingsDomainsRoute
  WWorkspacePProjectSettingsEnvRoute: typeof WWorkspacePProjectSettingsEnvRoute
  WWorkspacePProjectSettingsGeneralRoute: typeof WWorkspacePProjectSettingsGeneralRoute
  WWorkspacePProjectSettingsIntegrationsRoute: typeof WWorkspacePProjectSettingsIntegrationsRoute
  WWorkspacePProjectSettingsPlanRoute: typeof WWorkspacePProjectSettingsPlanRoute
  WWorkspacePProjectSettingsPublishingRoute: typeof WWorkspacePProjectSettingsPublishingRoute
  WWorkspacePProjectSettingsRedirectsRoute: typeof WWorkspacePProjectSettingsRedirectsRoute
  WWorkspacePProjectSettingsRobotsRoute: typeof WWorkspacePProjectSettingsRobotsRoute
  WWorkspacePProjectSettingsSeoRoute: typeof WWorkspacePProjectSettingsSeoRoute
  WWorkspacePProjectSettingsSetupRoute: typeof WWorkspacePProjectSettingsSetupRoute
  WWorkspacePProjectSettingsSitemapRoute: typeof WWorkspacePProjectSettingsSitemapRoute
  WWorkspacePProjectSettingsUsageRoute: typeof WWorkspacePProjectSettingsUsageRoute
  WWorkspacePProjectSettingsWebhooksRoute: typeof WWorkspacePProjectSettingsWebhooksRoute
}

const WWorkspacePProjectSettingsRouteChildren: WWorkspacePProjectSettingsRouteChildren =
  {
    WWorkspacePProjectSettingsAccessRoute:
      WWorkspacePProjectSettingsAccessRoute,
    WWorkspacePProjectSettingsAgentsRoute:
      WWorkspacePProjectSettingsAgentsRoute,
    WWorkspacePProjectSettingsApiRoute: WWorkspacePProjectSettingsApiRoute,
    WWorkspacePProjectSettingsBackupsRoute:
      WWorkspacePProjectSettingsBackupsRoute,
    WWorkspacePProjectSettingsBrandRoute: WWorkspacePProjectSettingsBrandRoute,
    WWorkspacePProjectSettingsCodeRoute: WWorkspacePProjectSettingsCodeRoute,
    WWorkspacePProjectSettingsDeliveryRoute:
      WWorkspacePProjectSettingsDeliveryRoute,
    WWorkspacePProjectSettingsDeploymentRoute:
      WWorkspacePProjectSettingsDeploymentRoute,
    WWorkspacePProjectSettingsDomainsRoute:
      WWorkspacePProjectSettingsDomainsRoute,
    WWorkspacePProjectSettingsEnvRoute: WWorkspacePProjectSettingsEnvRoute,
    WWorkspacePProjectSettingsGeneralRoute:
      WWorkspacePProjectSettingsGeneralRoute,
    WWorkspacePProjectSettingsIntegrationsRoute:
      WWorkspacePProjectSettingsIntegrationsRoute,
    WWorkspacePProjectSettingsPlanRoute: WWorkspacePProjectSettingsPlanRoute,
    WWorkspacePProjectSettingsPublishingRoute:
      WWorkspacePProjectSettingsPublishingRoute,
    WWorkspacePProjectSettingsRedirectsRoute:
      WWorkspacePProjectSettingsRedirectsRoute,
    WWorkspacePProjectSettingsRobotsRoute:
      WWorkspacePProjectSettingsRobotsRoute,
    WWorkspacePProjectSettingsSeoRoute: WWorkspacePProjectSettingsSeoRoute,
    WWorkspacePProjectSettingsSetupRoute: WWorkspacePProjectSettingsSetupRoute,
    WWorkspacePProjectSettingsSitemapRoute:
      WWorkspacePProjectSettingsSitemapRoute,
    WWorkspacePProjectSettingsUsageRoute: WWorkspacePProjectSettingsUsageRoute,
    WWorkspacePProjectSettingsWebhooksRoute:
      WWorkspacePProjectSettingsWebhooksRoute,
  }

const WWorkspacePProjectSettingsRouteWithChildren =
  WWorkspacePProjectSettingsRoute._addFileChildren(
    WWorkspacePProjectSettingsRouteChildren,
  )

interface WWorkspacePProjectRouteChildren {
  WWorkspacePProjectAgentRoute: typeof WWorkspacePProjectAgentRoute
  WWorkspacePProjectAiRoute: typeof WWorkspacePProjectAiRoute
  WWorkspacePProjectAnalyticsRoute: typeof WWorkspacePProjectAnalyticsRoute
  WWorkspacePProjectContentRoute: typeof WWorkspacePProjectContentRoute
  WWorkspacePProjectEditorRoute: typeof WWorkspacePProjectEditorRoute
  WWorkspacePProjectHostingRoute: typeof WWorkspacePProjectHostingRoute
  WWorkspacePProjectInstructionsRoute: typeof WWorkspacePProjectInstructionsRoute
  WWorkspacePProjectMediaRoute: typeof WWorkspacePProjectMediaRoute
  WWorkspacePProjectSchemaRoute: typeof WWorkspacePProjectSchemaRoute
  WWorkspacePProjectSearchRoute: typeof WWorkspacePProjectSearchRoute
  WWorkspacePProjectSeoRoute: typeof WWorkspacePProjectSeoRouteWithChildren
  WWorkspacePProjectSettingsRoute: typeof WWorkspacePProjectSettingsRouteWithChildren
  WWorkspacePProjectVisualRoute: typeof WWorkspacePProjectVisualRoute
  WWorkspacePProjectWorkflowRoute: typeof WWorkspacePProjectWorkflowRoute
  WWorkspacePProjectIndexRoute: typeof WWorkspacePProjectIndexRoute
  WWorkspacePProjectFormsFormIdRoute: typeof WWorkspacePProjectFormsFormIdRoute
  WWorkspacePProjectFormsIndexRoute: typeof WWorkspacePProjectFormsIndexRoute
  WWorkspacePProjectPagesPageIdSeoRoute: typeof WWorkspacePProjectPagesPageIdSeoRoute
}

const WWorkspacePProjectRouteChildren: WWorkspacePProjectRouteChildren = {
  WWorkspacePProjectAgentRoute: WWorkspacePProjectAgentRoute,
  WWorkspacePProjectAiRoute: WWorkspacePProjectAiRoute,
  WWorkspacePProjectAnalyticsRoute: WWorkspacePProjectAnalyticsRoute,
  WWorkspacePProjectContentRoute: WWorkspacePProjectContentRoute,
  WWorkspacePProjectEditorRoute: WWorkspacePProjectEditorRoute,
  WWorkspacePProjectHostingRoute: WWorkspacePProjectHostingRoute,
  WWorkspacePProjectInstructionsRoute: WWorkspacePProjectInstructionsRoute,
  WWorkspacePProjectMediaRoute: WWorkspacePProjectMediaRoute,
  WWorkspacePProjectSchemaRoute: WWorkspacePProjectSchemaRoute,
  WWorkspacePProjectSearchRoute: WWorkspacePProjectSearchRoute,
  WWorkspacePProjectSeoRoute: WWorkspacePProjectSeoRouteWithChildren,
  WWorkspacePProjectSettingsRoute: WWorkspacePProjectSettingsRouteWithChildren,
  WWorkspacePProjectVisualRoute: WWorkspacePProjectVisualRoute,
  WWorkspacePProjectWorkflowRoute: WWorkspacePProjectWorkflowRoute,
  WWorkspacePProjectIndexRoute: WWorkspacePProjectIndexRoute,
  WWorkspacePProjectFormsFormIdRoute: WWorkspacePProjectFormsFormIdRoute,
  WWorkspacePProjectFormsIndexRoute: WWorkspacePProjectFormsIndexRoute,
  WWorkspacePProjectPagesPageIdSeoRoute: WWorkspacePProjectPagesPageIdSeoRoute,
}

const WWorkspacePProjectRouteWithChildren =
  WWorkspacePProjectRoute._addFileChildren(WWorkspacePProjectRouteChildren)

interface WWorkspaceRouteChildren {
  WWorkspaceAgentRoute: typeof WWorkspaceAgentRoute
  WWorkspaceMembersRoute: typeof WWorkspaceMembersRoute
  WWorkspaceProjectsRoute: typeof WWorkspaceProjectsRoute
  WWorkspaceRolesRoute: typeof WWorkspaceRolesRoute
  WWorkspaceSettingsRoute: typeof WWorkspaceSettingsRouteWithChildren
  WWorkspaceIndexRoute: typeof WWorkspaceIndexRoute
  WWorkspacePProjectRoute: typeof WWorkspacePProjectRouteWithChildren
}

const WWorkspaceRouteChildren: WWorkspaceRouteChildren = {
  WWorkspaceAgentRoute: WWorkspaceAgentRoute,
  WWorkspaceMembersRoute: WWorkspaceMembersRoute,
  WWorkspaceProjectsRoute: WWorkspaceProjectsRoute,
  WWorkspaceRolesRoute: WWorkspaceRolesRoute,
  WWorkspaceSettingsRoute: WWorkspaceSettingsRouteWithChildren,
  WWorkspaceIndexRoute: WWorkspaceIndexRoute,
  WWorkspacePProjectRoute: WWorkspacePProjectRouteWithChildren,
}

const WWorkspaceRouteWithChildren = WWorkspaceRoute._addFileChildren(
  WWorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  DevScrollbarsRoute: DevScrollbarsRoute,
  PTokenRoute: PTokenRoute,
  WWorkspaceRoute: WWorkspaceRouteWithChildren,
  WorkspaceNewRoute: WorkspaceNewRoute,
  ApiPublicFormsFormIdSubmitRoute: ApiPublicFormsFormIdSubmitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
